#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
快速配置 LLM API Key - 交互式脚本
"""

import os
import sys

def quick_config():
    """快速交互式配置"""
    
    print("="*70)
    print("Quick LLM Configuration")
    print("="*70)
    
    print("\nSupported Providers:")
    print("1. OpenAI (GPT-4)      - Recommended")
    print("2. Anthropic (Claude)  - Excellent for coding")
    print("3. SiliconFlow         - Cheap Chinese option")
    print("4. Ollama              - Free local models")
    
    # 选择提供商
    while True:
        choice = input("\nSelect provider (1-4): ").strip()
        if choice in ['1', '2', '3', '4']:
            break
        print("Invalid choice, please try again")
    
    providers = {
        '1': {
            'name': 'OpenAI',
            'env': 'openai',
            'default_model': 'gpt-4o',
            'prompt': 'Enter OpenAI API Key (sk-...): '
        },
        '2': {
            'name': 'Anthropic',
            'env': 'anthropic',
            'default_model': 'claude-3-5-sonnet-latest',
            'prompt': 'Enter Anthropic API Key (sk-ant-...): '
        },
        '3': {
            'name': 'SiliconFlow',
            'env': 'siliconflow',
            'default_model': 'Qwen/Qwen2.5-7B-Instruct',
            'prompt': 'Enter SiliconFlow API Key: ',
            'base_url': 'https://api.siliconflow.cn/v1'
        },
        '4': {
            'name': 'Ollama',
            'env': 'ollama',
            'default_model': 'qwen2.5',
            'prompt': 'Press Enter for local model (no API key needed): '
        }
    }
    
    selected = providers[choice]
    
    # 输入 API Key
    api_key = input(selected['prompt']).strip()
    
    # 生成脚本
    print("\n" + "="*70)
    print("Generating startup script...")
    print("="*70)
    
    if api_key:
        script = f'''@echo off
REM Yunshu Smart Startup Script
REM Generated by quick_config.py

set LLM_PROVIDER={selected['env']}
set LLM_API_KEY={api_key}
set LLM_MODEL={selected['default_model']}'''
        
        if 'base_url' in selected:
            script += f'\nset LLM_BASE_URL={selected["base_url"]}'
        
        script += '\n\necho Starting Yunshu with Smart Mode...\necho.\npython main.py\n'
    else:
        script = f'''@echo off
REM Yunshu Smart Startup Script
REM Generated by quick_config.py

set LLM_PROVIDER={selected['env']}
set LLM_MODEL={selected['default_model']}

echo Starting Yunshu with {selected['name']}...
echo.\npython main.py\n'''
    
    # 保存脚本
    script_file = 'start_smart.bat'
    with open(script_file, 'w', encoding='utf-8') as f:
        f.write(script)
    
    print(f"\nSuccess! Created: {script_file}")
    print(f"\nTo start Yunshu with smart mode, run:")
    print(f"  .\\{script_file}")
    print("\nOr set environment variables manually:")
    print(f"  set LLM_PROVIDER={selected['env']}")
    print(f"  set LLM_API_KEY={api_key if api_key else '(not needed)'}")
    print(f"  set LLM_MODEL={selected['default_model']}")
    
    if api_key:
        print("\nOr add to system environment variables:")
        print(f"  LLM_PROVIDER={selected['env']}")
        print(f"  LLM_API_KEY={api_key}")
        print(f"  LLM_MODEL={selected['default_model']}")

if __name__ == "__main__":
    quick_config()
