<#
.SYNOPSIS
    Pre-commit Hook Fail-Safe 模块（可复用核心能力）

.DESCRIPTION
    从 sync_precommit_hook.ps1 提取的 fail-safe 核心逻辑，供其他脚本复用。
    三义校验：
    - 不易：hook 阈值 0 写死；hook 无 BOM / PS1 有 BOM 编码契约；已有 hook 必先备份
    - 变易：函数参数化，可被任意脚本 dot-source 或 Import-Module
    - 简易：每个函数单一职责，无外部依赖

    导出函数：
    - Get-HookContent        生成 hook bash 内容（含 marker 行）
    - Write-HookNoBom        写 hook 文件（UTF-8 无 BOM，bash 兼容）
    - Write-FileWithBom      写 PS1 脚本（UTF-8 with BOM，中文兼容）
    - Backup-ExistingHook    备份已有 hook 到时间戳文件
    - Test-HookUpToDate      幂等检测（内容比对）
    - Set-SourceRepoEnv      设置 TLM_HOOK_SOURCE_REPO 环境变量
    - Test-SourceRepoEnv     验证环境变量是否有效
    - Resolve-GitDir        解析 .git 真实路径（兼容 worktree/submodule）
    - Test-HookMarker        检测 hook 是否为本工具生成（含 marker）

.EXAMPLE
    # dot-source 方式复用
    . .\scripts\dev\hook_fail_safe.psm1
    $content = Get-HookContent -SourceRepo "C:\path\to\repo"
    Write-HookNoBom -Path "$repo\.git\hooks\pre-commit" -Content $content

    # Import-Module 方式复用
    Import-Module .\scripts\dev\hook_fail_safe.psm1 -Force
#>

# =================================================================
# 1. hook 内容模板（不易：模板锁定，阈值 0 写死）
# =================================================================
function Get-HookContent {
    <#
    .SYNOPSIS
        生成 pre-commit hook 的 bash 内容
    .DESCRIPTION
        三道 fail-safe 防护：
        1. TLM_HOOK_SOURCE_REPO 未设置 -> exit 1
        2. precheck_docs.ps1 不存在 -> exit 1
        3. powershell 调用失败 -> exit 1
    .PARAMETER SourceRepo
        源仓库根目录路径（写入 marker 行用于审计）
    .OUTPUTS
        [string] hook bash 脚本内容
    #>
    param([string]$SourceRepo)

    $lines = @(
        '#!/bin/bash',
        "# TLM-HOOK v1 source_repo=$SourceRepo",
        '# Auto-generated by scripts/dev/sync_precommit_hook.ps1',
        '# 全量预检：文档链接（阻塞）+ 锚点链接回归测试（git_precommit_check.ps1 编排）',
        '',
        'echo "[pre-commit] 运行全量预检（链接 + 锚点回归测试）..."',
        '# 通过环境变量 TLM_HOOK_SOURCE_REPO 间接寻址源仓库，hook 可复制到任意仓库',
        'if [ -z "$TLM_HOOK_SOURCE_REPO" ]; then',
        '    echo "[pre-commit][ERROR] TLM_HOOK_SOURCE_REPO 未设置，请运行 sync_precommit_hook.ps1" 1>&2',
        '    exit 1',
        'fi',
        '',
        'CHECK_PATH="$TLM_HOOK_SOURCE_REPO/scripts/dev/git_precommit_check.ps1"',
        'if [ ! -f "$CHECK_PATH" ]; then',
        '    echo "[pre-commit][ERROR] 通用检查脚本不存在: $CHECK_PATH" 1>&2',
        '    echo "  提示: 检查 TLM_HOOK_SOURCE_REPO 是否指向有效仓库根目录" 1>&2',
        '    exit 1',
        'fi',
        '',
        '# TLM_HOOK_VERBOSE=1 时开启字节级调试（-BomDiag），拦截失败输出 BOM/路径调试信息',
        'VERBOSE_ARG=""',
        'if [ "$TLM_HOOK_VERBOSE" = "1" ]; then',
        '    VERBOSE_ARG="-BomDiag"',
        'fi',
        '',
        'powershell -ExecutionPolicy Bypass -File "$CHECK_PATH" -TargetRepo "$(git rev-parse --show-toplevel)" $VERBOSE_ARG',
        'result=$?',
        'if [ $result -ne 0 ]; then',
        '    echo ""',
        '    echo "[pre-commit] 预检失败，提交被阻止"',
        '    echo "  修复方案: powershell -File \"$TLM_HOOK_SOURCE_REPO/scripts/dev/fix_broken_links.ps1\" -DryRun"',
        '    echo "  临时跳过: git commit --no-verify"',
        '    exit 1',
        'fi',
        'echo "[pre-commit] 预检通过"',
        '',
        '# ── PowerShell 编码检查(UTF-8 BOM 契约): 可选增强, 脚本存在才执行 ──',
        '# 检测 hook 关键文件(hook_fail_safe.psm1)是否丢失 BOM——PS 5.1 中文系统',
        '# 按 GBK 解码无 BOM 文件会乱码/解析失败(2026-08-03 事故复盘, 见',
        '# docs/observability/ps1_encoding_bom_troubleshooting.md)。',
        '# - BLOCK 级(关键文件缺 BOM/非法 UTF-8)阻止提交; 存量 WARN 仅提示不阻塞',
        '# - SKIP_ENCODING_CHECK=1 显式跳过; 脚本缺失时静默跳过(跨仓库安全)',
        'ENCODING_CHECK="$TLM_HOOK_SOURCE_REPO/scripts/check_ps1_encoding.py"',
        'if [ -f "$ENCODING_CHECK" ]; then',
        '    if [ -n "$SKIP_ENCODING_CHECK" ]; then',
        '        echo "[pre-commit][WARN] SKIP_ENCODING_CHECK=1, 跳过编码检查" 1>&2',
        '    else',
        '        echo "[pre-commit] 运行 PowerShell 编码检查(UTF-8 BOM)..."',
        '        python "$ENCODING_CHECK" --quiet --repo-root "$TLM_HOOK_SOURCE_REPO"',
        '        enc_result=$?',
        '        if [ $enc_result -ne 0 ]; then',
        '            echo "" 1>&2',
        '            echo "[pre-commit][ERROR] 编码检查未通过, 提交被阻止" 1>&2',
        '            echo "  修复: python \\"$ENCODING_CHECK\\" --fix --repo-root \\"$TLM_HOOK_SOURCE_REPO\\"" 1>&2',
        '            echo "  临时跳过: SKIP_ENCODING_CHECK=1 git commit 或 git commit --no-verify" 1>&2',
        '            exit 1',
        '        fi',
        '        echo "[pre-commit] 编码检查通过"',
        '    fi',
        'else',
        '    echo "[pre-commit][INFO] 编码检查脚本不存在, 跳过(跨仓库安全)" 1>&2',
        'fi',
        '',
        '# ── CI 守卫(reranker-timeout-guard 模拟): 可选增强, 脚本存在才执行 ──',
        '# 复用 simulate_ci_guard_failure.py 的判定链(exit 0=允许/1=阻止)。',
        '# - 脚本缺失时静默跳过(守【不易】: hook 可复制到任意仓库, 不因缺脚本误阻塞)',
        '# - SKIP_CI_GUARD=1 显式跳过(本地临时豁免)',
        '# - 守卫失败 exit 1 阻止提交(与 GH Actions 阻止 PR 合并语义一致)',
        'CI_GUARD="$TLM_HOOK_SOURCE_REPO/scripts/simulate_ci_guard_failure.py"',
        'if [ -f "$CI_GUARD" ]; then',
        '    if [ -n "$SKIP_CI_GUARD" ]; then',
        '        echo "[pre-commit][WARN] SKIP_CI_GUARD=1, 跳过 CI 守卫检查" 1>&2',
        '    else',
        '        echo "[pre-commit] 运行 CI 守卫检查(reranker-timeout-guard 模拟)..."',
        '        python "$CI_GUARD" --assert-allowed',
        '        guard_result=$?',
        '        if [ $guard_result -ne 0 ]; then',
        '            echo "" 1>&2',
        '            echo "[pre-commit][ERROR] CI 守卫未通过, 提交被阻止" 1>&2',
        '            echo "  临时跳过: SKIP_CI_GUARD=1 git commit 或 git commit --no-verify" 1>&2',
        '            exit 1',
        '        fi',
        '        echo "[pre-commit] CI 守卫通过"',
        '    fi',
        'else',
        '    echo "[pre-commit][INFO] CI 守卫脚本不存在, 跳过(跨仓库安全)" 1>&2',
        'fi',
        '',
        '# ── 核心不变量校验(tool_trace 计数机制 / hook 三段式模板): 可选增强 ──',
        '# 2026-08-04 回滚复盘: tool_trace.py 计数机制与 hook 模板曾被回滚, git 历史',
        '# 无对应提交导致静默回归(见 docs/observability/rollback_recovery_report.md)。',
        '# 静态校验关键文件不变量, 被破坏 → BLOCK exit 1 阻止提交。',
        '# - SKIP_INVARIANT=1 显式跳过; 脚本缺失时静默跳过(跨仓库安全)',
        'INVARIANT="$TLM_HOOK_SOURCE_REPO/scripts/verify_core_invariants.py"',
        'if [ -f "$INVARIANT" ]; then',
        '    if [ -n "$SKIP_INVARIANT" ]; then',
        '        echo "[pre-commit][WARN] SKIP_INVARIANT=1, 跳过核心不变量校验" 1>&2',
        '    else',
        '        echo "[pre-commit] 运行核心不变量校验..."',
        '        python "$INVARIANT" --quiet --repo-root "$TLM_HOOK_SOURCE_REPO"',
        '        inv_result=$?',
        '        if [ $inv_result -ne 0 ]; then',
        '            echo "" 1>&2',
        '            echo "[pre-commit][ERROR] 核心不变量校验未通过, 提交被阻止" 1>&2',
        '            echo "  修复: 按 docs/observability/rollback_recovery_report.md 恢复不变量" 1>&2',
        '            echo "  临时跳过: SKIP_INVARIANT=1 git commit 或 git commit --no-verify" 1>&2',
        '            exit 1',
        '        fi',
        '        echo "[pre-commit] 核心不变量校验通过"',
        '    fi',
        'else',
        '    echo "[pre-commit][INFO] 不变量校验脚本不存在, 跳过(跨仓库安全)" 1>&2',
        'fi',
        'exit 0'
    )
    return ($lines -join "`n") + "`n"
}

# =================================================================
# 1.1 pre-push hook 内容模板（不易：push 前核心不变量校验）
# =================================================================
function Get-PrePushContent {
    <#
    .SYNOPSIS
        生成 pre-push hook 的 bash 内容
    .DESCRIPTION
        push 前运行核心不变量校验(verify_core_invariants.py):
        - 不变量被破坏 → BLOCK exit 1 阻止 push
        - TLM_HOOK_SOURCE_REPO 未设置 → exit 1
        - SKIP_INVARIANT=1 显式跳过; 脚本缺失静默跳过(跨仓库安全)
        预检/编码检查/CI 守卫由 pre-commit 覆盖, pre-push 仅保留不变量校验。
    .PARAMETER SourceRepo
        源仓库根目录路径（写入 marker 行用于审计）
    .OUTPUTS
        [string] hook bash 脚本内容
    #>
    param([string]$SourceRepo)

    $lines = @(
        '#!/bin/bash',
        "# TLM-HOOK-PREPUSH v1 source_repo=$SourceRepo",
        '# Auto-generated by scripts/dev/sync_precommit_hook.ps1',
        '# push 前核心不变量校验: 不变量被破坏 → BLOCK exit 1 阻止 push',
        '',
        'echo "[pre-push] 运行核心不变量校验(tool_trace 计数机制 / hook 模板)..."',
        '# 通过环境变量 TLM_HOOK_SOURCE_REPO 间接寻址源仓库, hook 可复制到任意仓库',
        'if [ -z "$TLM_HOOK_SOURCE_REPO" ]; then',
        '    echo "[pre-push][ERROR] TLM_HOOK_SOURCE_REPO 未设置，请运行 sync_precommit_hook.ps1" 1>&2',
        '    exit 1',
        'fi',
        '',
        '# ── 核心不变量校验(2026-08-04 回滚复盘): 被破坏 → 阻止 push ──',
        '# 静态校验关键文件不变量, 与 pre-commit 的 INVARIANT 段同源(同一判定)。',
        '# - SKIP_INVARIANT=1 显式跳过; 脚本缺失时静默跳过(跨仓库安全)',
        'INVARIANT="$TLM_HOOK_SOURCE_REPO/scripts/verify_core_invariants.py"',
        'if [ -f "$INVARIANT" ]; then',
        '    if [ -n "$SKIP_INVARIANT" ]; then',
        '        echo "[pre-push][WARN] SKIP_INVARIANT=1, 跳过核心不变量校验" 1>&2',
        '    else',
        '        echo "[pre-push] 运行核心不变量校验..."',
        '        python "$INVARIANT" --quiet --repo-root "$TLM_HOOK_SOURCE_REPO"',
        '        inv_result=$?',
        '        if [ $inv_result -ne 0 ]; then',
        '            echo "" 1>&2',
        '            echo "[pre-push][ERROR] 核心不变量校验未通过, push 被阻止" 1>&2',
        '            echo "  修复: 按 docs/observability/rollback_recovery_report.md 恢复不变量" 1>&2',
        '            echo "  临时跳过: SKIP_INVARIANT=1 git push 或 git push --no-verify" 1>&2',
        '            exit 1',
        '        fi',
        '        echo "[pre-push] 核心不变量校验通过"',
        '    fi',
        'else',
        '    echo "[pre-push][INFO] 不变量校验脚本不存在, 跳过(跨仓库安全)" 1>&2',
        'fi',
        'exit 0'
    )
    return ($lines -join "`n") + "`n"
}

# =================================================================
# 2. 文件写入：BOM 编码契约（不易）
# =================================================================
function Write-HookNoBom {
    <#
    .SYNOPSIS
        写 hook 文件（UTF-8 无 BOM，bash 兼容）
    .DESCRIPTION
        bash 不识别带 BOM 的 shebang #!/bin/bash，必须无 BOM。
        不使用 Set-Content（PS 5.1 默认加 BOM）。
    #>
    param([string]$Path, [string]$Content)
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function Write-FileWithBom {
    <#
    .SYNOPSIS
        写 PS1 脚本文件（UTF-8 with BOM，PowerShell 5.1 中文兼容）
    .DESCRIPTION
        PS 5.1 在中文系统下默认 GBK 解码，无 BOM 会导致中文乱码。
    #>
    param([string]$Path, [string]$Content)
    $utf8WithBom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8WithBom)
}

# =================================================================
# 3. 备份逻辑（不易：先备份后覆盖）
# =================================================================
function Backup-ExistingHook {
    <#
    .SYNOPSIS
        备份已有 hook 到时间戳文件
    .DESCRIPTION
        - 跳过 pre-commit.bak.* 自身（避免链式备份）
        - 跳过 *.sample（git 自带模板）
        - 同秒重复运行自动追加序号 .1/.2
    .PARAMETER HookPath
        hook 文件路径
    .PARAMETER DryRun
        DryRun 模式下不实际复制
    .OUTPUTS
        [string] 备份文件路径，无需备份时返回 $null
    #>
    param(
        [string]$HookPath,
        [switch]$DryRun
    )
    if (-not (Test-Path $HookPath)) { return $null }

    $fileName = Split-Path $HookPath -Leaf
    if ($fileName -like "pre-commit.bak.*") { return $null }
    if ($fileName -like "*.sample") { return $null }

    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $bakPath = "$HookPath.bak.$timestamp"

    $seq = 1
    while (Test-Path $bakPath) {
        $bakPath = "$HookPath.bak.$timestamp.$seq"
        $seq++
    }

    if (-not $DryRun) {
        Copy-Item -Path $HookPath -Destination $bakPath -Force
    }
    return $bakPath
}

# =================================================================
# 4. 幂等性检测（变易：已是最新则跳过）
# =================================================================
function Test-HookUpToDate {
    <#
    .SYNOPSIS
        检测 hook 是否已是最新版本
    .DESCRIPTION
        内容比对前归一化 CRLF/LF，避免编辑器换行差异误判。
    .OUTPUTS
        [bool] $true 表示已是最新可跳过
    #>
    param([string]$HookPath, [string]$NewContent)
    if (-not (Test-Path $HookPath)) { return $false }
    $current = [System.IO.File]::ReadAllText($HookPath, [System.Text.Encoding]::UTF8)
    $currentNorm = $current -replace "`r`n", "`n"
    $newNorm     = $NewContent -replace "`r`n", "`n"
    return $currentNorm -eq $newNorm
}

# =================================================================
# 5. 环境变量管理（变易：可重指向）
# =================================================================
function Set-SourceRepoEnv {
    <#
    .SYNOPSIS
        设置 TLM_HOOK_SOURCE_REPO 环境变量（User 级 + 当前进程）
    .DESCRIPTION
        - User 级：跨进程持久，不需要管理员权限
        - 当前进程 $env:：保证同会话内立即可用
    .PARAMETER Path
        源仓库根目录路径
    .PARAMETER DryRun
        DryRun 模式下只打印不写入
    #>
    param(
        [string]$Path,
        [switch]$DryRun
    )
    if ($DryRun) {
        Write-Host "  [DryRun] 将设置 User 级 TLM_HOOK_SOURCE_REPO = $Path" -ForegroundColor Yellow
        return
    }
    [System.Environment]::SetEnvironmentVariable('TLM_HOOK_SOURCE_REPO', $Path, 'User')
    $env:TLM_HOOK_SOURCE_REPO = $Path
    Write-Host "  [OK] TLM_HOOK_SOURCE_REPO = $Path (User 级 + 当前进程)" -ForegroundColor Green
}

function Test-SourceRepoEnv {
    <#
    .SYNOPSIS
        验证 TLM_HOOK_SOURCE_REPO 环境变量是否有效
    .DESCRIPTION
        检查：1) 变量已设置 2) 路径存在 3) precheck_docs.ps1 存在
    .OUTPUTS
        [hashtable] @{ Valid = $bool; Value = $string; Error = $string }
    #>
    $result = @{ Valid = $false; Value = $null; Error = $null }
    $envRepo = [System.Environment]::GetEnvironmentVariable('TLM_HOOK_SOURCE_REPO','User')
    $result.Value = $envRepo

    if (-not $envRepo) {
        $result.Error = 'TLM_HOOK_SOURCE_REPO 未设置（请运行 sync_precommit_hook.ps1）'
        return $result
    }
    if (-not (Test-Path $envRepo)) {
        $result.Error = "TLM_HOOK_SOURCE_REPO 指向的路径不存在: $envRepo"
        return $result
    }
    $ps1Path = Join-Path $envRepo "scripts\dev\precheck_docs.ps1"
    if (-not (Test-Path $ps1Path)) {
        $result.Error = "源仓库脚本不存在: $ps1Path"
        return $result
    }
    $result.Valid = $true
    return $result
}

# =================================================================
# 6. .git 路径解析（变易：兼容 worktree/submodule）
# =================================================================
function Resolve-GitDir {
    <#
    .SYNOPSIS
        解析 .git 真实路径
    .DESCRIPTION
        .git 为文件（worktree/submodule）时，解析 gitdir: 指针。
        .git 为目录时，直接返回。
    .OUTPUTS
        [string] .git 真实目录路径，非 git 仓库返回 $null
    #>
    param([string]$RepoPath)
    $gitPath = Join-Path $RepoPath ".git"
    if (-not (Test-Path $gitPath)) { return $null }

    if (Test-Path $gitPath -PathType Leaf) {
        $content = [System.IO.File]::ReadAllText($gitPath, [System.Text.Encoding]::UTF8)
        if ($content -match 'gitdir:\s*(.+)') {
            $gitDir = $Matches[1].Trim()
            if (-not ([System.IO.Path]::IsPathRooted($gitDir))) {
                $gitDir = [System.IO.Path]::GetFullPath((Join-Path $RepoPath $gitDir))
            }
            return $gitDir
        }
        return $null
    }
    return $gitPath
}

# =================================================================
# 7. hook marker 检测（变易：识别本工具生成的 hook）
# =================================================================
function Test-HookMarker {
    <#
    .SYNOPSIS
        检测 hook 是否为本工具生成（含 TLM-HOOK v1 marker）
    .OUTPUTS
        [hashtable] @{ IsOurs = $bool; SourceRepo = $string; Threshold = $string }
    #>
    param([string]$HookPath)
    $result = @{ IsOurs = $false; SourceRepo = $null; Threshold = $null }
    if (-not (Test-Path $HookPath)) { return $result }

    $content = [System.IO.File]::ReadAllText($HookPath, [System.Text.Encoding]::UTF8)
    # 用 [^\r\n]+ 匹配到行尾，避免 $ 在多行模式下的歧义
    if ($content -match 'TLM-HOOK v1 source_repo=([^\r\n]+)') {
        $result.IsOurs = $true
        $result.SourceRepo = $Matches[1].Trim()
    }
    if ($content -match '-AllowBroken\s+(\d+)') {
        $result.Threshold = $Matches[1]
    }
    return $result
}

# =================================================================
# 8. 钩子权限检测与修复（变易：跨平台兼容 Windows ACL + Unix chmod）
# =================================================================
function Test-HookExecutable {
    <#
    .SYNOPSIS
        检测 hook 文件是否可执行（跨平台）
    .DESCRIPTION
        - Unix: 检查文件是否有执行位（用 stat -c %a 或 git update-index --chmod=）
        - Windows: 检查文件是否只读 + 当前用户是否有写入权限
    .OUTPUTS
        [hashtable] @{ IsExecutable = $bool; Platform = $string; Issues = @() }
    #>
    param([string]$HookPath)
    $result = @{ IsExecutable = $true; Platform = $null; Issues = @() }

    if (-not (Test-Path $HookPath)) {
        $result.IsExecutable = $false
        $result.Issues += 'hook 文件不存在'
        return $result
    }

    # 平台检测
    $isWindows = ($PSVersionTable.Platform -ne 'Unix') -and ($env:OS -eq 'Windows_NT')
    $result.Platform = if ($isWindows) { 'Windows' } else { 'Unix' }

    if ($isWindows) {
        # Windows: 检查只读属性
        $fileInfo = Get-Item $HookPath -Force
        if ($fileInfo.IsReadOnly) {
            $result.IsExecutable = $false
            $result.Issues += '文件被设置为只读'
        }
        # 检查 ACL 是否允许当前用户写入
        try {
            $acl = Get-Acl $HookPath -ErrorAction Stop
            $currentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
            $rules = $acl.GetAccessRules($true, $true, [System.Security.Principal.SecurityIdentifier])
            $canWrite = $false
            foreach ($rule in $rules) {
                if ($rule.AccessControlType -eq 'Allow' -and
                    $rule.RegistryRights -band [System.Security.AccessControl.FileSystemRights]::Modify -or
                    $rule.FileSystemRights -band [System.Security.AccessControl.FileSystemRights]::Write) {
                    # 检查是否应用于当前用户或所属组
                    if ($currentIdentity.User -eq $rule.IdentityReference -or
                        ($currentIdentity.Groups | ForEach-Object { $_ }) -contains $rule.IdentityReference) {
                        $canWrite = $true
                        break
                    }
                }
            }
            if (-not $canWrite) {
                # 简化检查：若 ACL 复杂判断不准，只标记只读问题
                # 真正的 ACL 修复在 Repair-HookPermission 中处理
            }
        } catch {
            # ACL 读取失败不阻塞，只记录
            $result.Issues += "ACL 读取失败: $($_.Exception.Message)"
        }
    } else {
        # Unix: 检查执行位（mode 末位奇数表示 owner 有执行位）
        $modeStr = & stat -c '%a' $HookPath 2>&1
        if ($LASTEXITCODE -eq 0) {
            $mode = $modeStr.ToString().Trim()
            # [Convert]::ToInt32('111', 8) 为 PS 5.1 兼容写法（避免 0o111 PS7+ 语法）
            $execBits = [Convert]::ToInt32('111', 8)
            $modeInt = [Convert]::ToInt32($mode, 8)
            $hasExec = ($modeInt -band $execBits) -ne 0
            if (-not $hasExec) {
                $result.IsExecutable = $false
                $result.Issues += "文件无执行位 (mode=$modeStr)"
            }
        }
    }

    return $result
}

function Repair-HookPermission {
    <#
    .SYNOPSIS
        自动修复 hook 文件权限冲突
    .DESCRIPTION
        - Windows: 移除只读属性 + 重置 ACL 允许当前用户完全控制
        - Unix: chmod +x 添加执行位
        - 失败时返回详细错误信息，不抛异常（fail-soft，由调用者决定是否阻塞）
    .PARAMETER HookPath
        hook 文件路径
    .OUTPUTS
        [hashtable] @{ Repaired = $bool; Actions = @(); Error = $string }
    #>
    param([string]$HookPath)
    $result = @{ Repaired = $false; Actions = @(); Error = $null }

    if (-not (Test-Path $HookPath)) {
        $result.Error = 'hook 文件不存在，无法修复权限'
        return $result
    }

    $isWindows = ($PSVersionTable.Platform -ne 'Unix') -and ($env:OS -eq 'Windows_NT')

    try {
        if ($isWindows) {
            # 1. 移除只读属性
            $fileInfo = Get-Item $HookPath -Force
            if ($fileInfo.IsReadOnly) {
                $fileInfo.IsReadOnly = $false
                $fileInfo.Refresh()
                $result.Actions += '移除只读属性'
            }

            # 2. 重置 ACL：确保当前用户有完全控制权
            $currentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
            $acl = Get-Acl $HookPath -ErrorAction Stop

            # 检查是否已有当前用户的规则
            $hasWriteRule = $false
            foreach ($rule in $acl.GetAccessRules($true, $true, [System.Security.Principal.SecurityIdentifier])) {
                if ($rule.AccessControlType -eq 'Allow' -and
                    ($rule.FileSystemRights -band [System.Security.AccessControl.FileSystemRights]::Write)) {
                    $hasWriteRule = $true
                    break
                }
            }

            if (-not $hasWriteRule) {
                $rights = [System.Security.AccessControl.FileSystemRights]::FullControl
                $inheritance = [System.Security.AccessControl.InheritanceFlags]::None
                $propagation = [System.Security.AccessControl.PropagationFlags]::None
                $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
                    $currentIdentity.Name, $rights, $inheritance, $propagation, 'Allow'
                )
                $acl.AddAccessRule($rule)
                Set-Acl -Path $HookPath -AclObject $acl -ErrorAction Stop
                $result.Actions += "添加 ACL 规则: $($currentIdentity.Name) FullControl"
            }

            $result.Repaired = $true
        } else {
            # Unix: chmod +x
            & chmod +x $HookPath 2>&1
            if ($LASTEXITCODE -eq 0) {
                $result.Actions += 'chmod +x 添加执行位'
                $result.Repaired = $true
            } else {
                $result.Error = "chmod +x 失败 (exit=$LASTEXITCODE)"
            }
        }
    } catch {
        $result.Error = $_.Exception.Message
    }

    return $result
}

function Invoke-SafeHookWrite {
    <#
    .SYNOPSIS
        安全写入 hook 文件（含权限自动修复）
    .DESCRIPTION
        复合操作：写入 hook -> 检测权限 -> 必要时修复 -> 再次验证
        任意步骤失败都返回详细错误，不抛异常。
        调用者可根据 Repaired 字段决定是否提示用户。
    .PARAMETER HookPath
        hook 文件路径
    .PARAMETER Content
        hook 内容
    .OUTPUTS
        [hashtable] @{ Written = $bool; PermissionOk = $bool; Repaired = $bool; Actions = @(); Error = $string }
    #>
    param([string]$HookPath, [string]$Content)
    $result = @{
        Written = $false; PermissionOk = $false; Repaired = $false
        Actions = @(); Error = $null
    }

    # 1. 尝试写入
    try {
        Write-HookNoBom -Path $HookPath -Content $Content
        $result.Written = $true
        $result.Actions += 'hook 已写入'
    } catch {
        # 第一次写入失败：可能权限不足，尝试修复
        $result.Error = "首次写入失败: $($_.Exception.Message)"
        $repair = Repair-HookPermission -HookPath $HookPath
        $result.Actions += $repair.Actions
        if (-not $repair.Repaired) {
            $result.Error += " | 权限修复失败: $($repair.Error)"
            return $result
        }
        $result.Repaired = $true
        # 修复后重试
        try {
            Write-HookNoBom -Path $HookPath -Content $Content
            $result.Written = $true
            $result.Actions += '权限修复后重试写入成功'
        } catch {
            $result.Error += " | 修复后仍写入失败: $($_.Exception.Message)"
            return $result
        }
    }

    # 2. 验证权限
    $permCheck = Test-HookExecutable -HookPath $HookPath
    if ($permCheck.IsExecutable) {
        $result.PermissionOk = $true
    } else {
        # 尝试修复权限
        $repair = Repair-HookPermission -HookPath $HookPath
        $result.Actions += $repair.Actions
        if ($repair.Repaired) {
            $result.Repaired = $true
            # 再次验证
            $permCheck2 = Test-HookExecutable -HookPath $HookPath
            $result.PermissionOk = $permCheck2.IsExecutable
            if (-not $result.PermissionOk) {
                $result.Error = "权限修复后仍不可执行: $($permCheck2.Issues -join '; ')"
            }
        } else {
            $result.Error = "权限修复失败: $($repair.Error)"
        }
    }

    return $result
}

# =================================================================
# 9. hook 退出码解释层（变易：新增能力，不修改既有函数契约）
# =================================================================
# 设计说明：
# - 不易：不修改 Get-HookContent 生成的 hook 内容（exit 1 阻塞语义不变，已分发旧 hook 不受影响）
# - 变易：通过 stderr 文本回溯区分 exit 1 的 3 种具体原因；2/3/4 作为预留码供未来 -ExitCodeScheme v2 启用
# - 简易：用 OrderedDictionary，不引入 enum 类型
# =================================================================
function Get-HookExitCodeMap {
    <#
    .SYNOPSIS
        返回 hook 退出码 → 含义映射表（有序）
    .DESCRIPTION
        - 0=Success / 1=PreCheckFailed（兼容现有 hook）
        - 2=EnvNotSet / 3=ScriptMissing / 4=PreCheckExecFailed（预留码，当前 hook 不输出）
        - 126=PermissionDenied / 127=CommandNotFound / 130/137/143=Signal（bash 标准）
        每个 entry: @{ Category; Meaning; Remediation; StderrPattern }
    .PARAMETER IncludeBashStandard
        是否包含 126/127/128+N bash 标准退出码（默认包含；显式传 -IncludeBashStandard:$false 可排除）
    .OUTPUTS
        [hashtable] 键=[int]exit code，值=[hashtable]@{ Category; Meaning; Remediation; StderrPattern }
    #>
    param([switch]$IncludeBashStandard)

    # 默认包含 bash 标准码（switch 未传时 $IncludeBashStandard 为 $false，需显式判断未传状态）
    $includeBash = if ($PSBoundParameters.ContainsKey('IncludeBashStandard')) { $IncludeBashStandard } else { $true }

    # 用 hashtable + int key（PS 5.1 下 [ordered]@{} 用 int key 读写会触发只读 int 索引器导致异常）
    # 顺序由调用者按 key 排序展示（错误码表数量少，顺序非功能性需求）
    $map = @{}
    $map[0]   = @{ Category='Success';            Meaning='hook 通过';                              Remediation=$null;                       StderrPattern=$null }
    $map[1]   = @{ Category='PreCheckFailed';     Meaning='通用预检失败（需查 stderr 区分）';        Remediation='见 stderr 回溯';              StderrPattern=$null }
    $map[2]   = @{ Category='EnvNotSet';          Meaning='TLM_HOOK_SOURCE_REPO 未设置';            Remediation='运行 sync_precommit_hook.ps1'; StderrPattern='TLM_HOOK_SOURCE_REPO 未设置' }
    $map[3]   = @{ Category='ScriptMissing';      Meaning='源仓库 precheck_docs.ps1 不存在';        Remediation='检查 TLM_HOOK_SOURCE_REPO 路径'; StderrPattern='源仓库脚本不存在' }
    $map[4]   = @{ Category='PreCheckExecFailed'; Meaning='powershell 预检执行失败';                Remediation='运行 fix_broken_links.ps1 -DryRun'; StderrPattern='预检失败，提交被阻止' }

    if ($includeBash) {
        $map[126] = @{ Category='PermissionDenied'; Meaning='命令不可执行（权限）'; Remediation='Repair-HookPermission 或 chmod +x'; StderrPattern=$null }
        $map[127] = @{ Category='CommandNotFound';  Meaning='命令未找到';          Remediation='检查 PATH / powershell 安装';       StderrPattern=$null }
        $map[130] = @{ Category='Signal';           Meaning='SIGINT (Ctrl+C)';    Remediation='检查是否被中断';                    StderrPattern=$null }
        $map[137] = @{ Category='Signal';           Meaning='SIGKILL';            Remediation='检查 OOM / 强制终止';               StderrPattern=$null }
        $map[143] = @{ Category='Signal';           Meaning='SIGTERM';            Remediation='检查终止信号来源';                  StderrPattern=$null }
    }
    return $map
}

function Resolve-HookExitCode {
    <#
    .SYNOPSIS
        解释 hook exit code 的具体含义
    .DESCRIPTION
        - 不易：exit 1 永远映射到 PreCheckFailed（不静默通过失败）
        - 变易：当提供 -Stderr 时，通过文本回溯区分 exit 1 的 3 种具体原因
        - 简易：返回单一 hashtable，不抛异常
    .PARAMETER ExitCode
        hook 进程退出码
    .PARAMETER Stderr
        可选：hook 的 stderr 输出，用于 exit 1 时回溯具体原因
    .PARAMETER IncludeBashStandard
        是否在未知码时回退到 bash 标准码表（默认包含；显式传 -IncludeBashStandard:$false 可排除）
    .OUTPUTS
        [hashtable] @{ Code; Category; Meaning; Remediation; Matched; SubCategory }
    #>
    param(
        [Parameter(Mandatory)][int]$ExitCode,
        [string]$Stderr,
        [switch]$IncludeBashStandard
    )
    # 默认包含 bash 标准码（switch 未传时视为 true）
    if (-not $PSBoundParameters.ContainsKey('IncludeBashStandard')) {
        $map = Get-HookExitCodeMap
    } else {
        $map = Get-HookExitCodeMap -IncludeBashStandard:$IncludeBashStandard
    }
    $result = @{
        Code=$ExitCode; Category='Unknown'; Meaning="未知退出码: $ExitCode"
        Remediation=$null; Matched=$false; SubCategory=$null
    }
    if ($map.Contains($ExitCode)) {
        $entry = $map[$ExitCode]
        $result.Category     = $entry.Category
        $result.Meaning      = $entry.Meaning
        $result.Remediation  = $entry.Remediation
        $result.Matched      = $true

        # exit 1 时通过 stderr 回溯具体子类（不易：不改变 exit 1 阻塞语义）
        if ($ExitCode -eq 1 -and $Stderr) {
            foreach($code in @(2,3,4)) {
                $pattern = $map[$code].StderrPattern
                if ($pattern -and ($Stderr -match [regex]::Escape($pattern))) {
                    $result.SubCategory  = $map[$code].Category
                    $result.Meaning      = $map[$code].Meaning
                    $result.Remediation  = $map[$code].Remediation
                    break
                }
            }
        }
    } elseif ($ExitCode -gt 128 -and $ExitCode -lt 256) {
        $result.Category = 'Signal'
        $result.Meaning  = "bash 信号终止 (signal $($ExitCode - 128))"
        $result.Matched  = $true
    }
    return $result
}

function Invoke-HookWithCapture {
    <#
    .SYNOPSIS
        执行 hook 并捕获 exit code + stdout + stderr
    .DESCRIPTION
        - 不易：超时不静默通过，返回非零 exit code（避免 hook 卡死导致提交误通过）
        - 变易：-Resolve 自动调用 Resolve-HookExitCode 解释结果
        - 简易：用 System.Diagnostics.Process，不依赖外部模块
    .PARAMETER HookPath
        hook 文件路径
    .PARAMETER Arguments
        传给 hook 的参数数组
    .PARAMETER TimeoutSec
        超时秒数（默认 60），超时返回 exit code 124
    .PARAMETER Resolve
        自动在返回结果的 Resolved 字段填充解释
    .OUTPUTS
        [hashtable] @{ ExitCode; Stdout; Stderr; TimedOut; Resolved }
    #>
    param(
        [Parameter(Mandatory)][string]$HookPath,
        [string[]]$Arguments = @(),
        [int]$TimeoutSec = 60,
        [switch]$Resolve
    )
    $result = @{ ExitCode=-1; Stdout=''; Stderr=''; TimedOut=$false; Resolved=$null }

    # 路径存在性检查：纯文件名（无分隔符）依赖 PATH 查找，跳过 Test-Path；绝对/相对路径才检查
    $isPlainName = $HookPath -notmatch '[/\\]'
    if (-not $isPlainName -and -not (Test-Path $HookPath)) {
        $result.ExitCode = 127
        $result.Stderr    = "[Invoke-HookWithCapture] hook file not found: $HookPath"
        if ($Resolve) { $result.Resolved = Resolve-HookExitCode -ExitCode 127 -IncludeBashStandard }
        return $result
    }

    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName               = $HookPath
    $psi.Arguments              = ($Arguments -join ' ')
    $psi.UseShellExecute        = $false
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError  = $true
    $psi.CreateNoWindow         = $true
    # 强制 UTF-8 读取 stdout/stderr（避免中文系统下 GBK 编码导致中文 stderr 损坏）
    $psi.StandardOutputEncoding = [System.Text.Encoding]::UTF8
    $psi.StandardErrorEncoding  = [System.Text.Encoding]::UTF8

    $proc = New-Object System.Diagnostics.Process
    $proc.StartInfo = $psi

    try {
        [void]$proc.Start()
    } catch {
        # Process.Start 失败（文件不存在/无执行权限/不是有效可执行文件）
        $result.ExitCode = 127
        $result.Stderr    = "[Invoke-HookWithCapture] failed to start: $($_.Exception.Message)"
        if ($Resolve) { $result.Resolved = Resolve-HookExitCode -ExitCode 127 -IncludeBashStandard }
        return $result
    }
    # 同步读取 stdout/stderr（比异步事件更简单可靠，避免 PS 5.1 事件竞态）
    # 注意：先 ReadToEndAsync 再 WaitForExit，避免死锁（进程 stdout buffer 满会阻塞）
    $stdoutTask = $proc.StandardOutput.ReadToEndAsync()
    $stderrTask = $proc.StandardError.ReadToEndAsync()
    $exited = $proc.WaitForExit($TimeoutSec * 1000)
    if (-not $exited) {
        try { $proc.Kill() } catch {}
        $result.TimedOut = $true
        $result.ExitCode = 124
        $result.Stderr   = "[Invoke-HookWithCapture] timeout after ${TimeoutSec}s"
        # 仍尝试读取已缓冲的输出
        try {
            $result.Stdout = $stdoutTask.Result
            $result.Stderr += "`n" + $stderrTask.Result
        } catch {}
    } else {
        # 等待异步读取完成（进程已退出，数据已就绪）
        $result.ExitCode = $proc.ExitCode
        $result.Stdout   = $stdoutTask.Result
        $result.Stderr   = $stderrTask.Result
    }

    if ($Resolve) {
        $result.Resolved = Resolve-HookExitCode -ExitCode $result.ExitCode -Stderr $result.Stderr -IncludeBashStandard
    }
    return $result
}

# 导出所有函数（15 原有 + 1 新增 = 16）
Export-ModuleMember -Function Get-HookContent, Get-PrePushContent, Write-HookNoBom, Write-FileWithBom, Backup-ExistingHook, Test-HookUpToDate, Set-SourceRepoEnv, Test-SourceRepoEnv, Resolve-GitDir, Test-HookMarker, Test-HookExecutable, Repair-HookPermission, Invoke-SafeHookWrite, Get-HookExitCodeMap, Resolve-HookExitCode, Invoke-HookWithCapture
