#
# Module manifest for module 'tlm-hook-failsafe'
#
# Generated by: agent-team
#
# Generated on: 2026/7/29
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'tlm-hook-failsafe.psm1'

# Version number of this module.
ModuleVersion = '1.1.10'

# Supported PSEditions
CompatiblePSEditions = 'Desktop', 'Core'

# ID used to uniquely identify this module
GUID = 'b3c4d5e6-f7a8-4b9c-0d1e-2f3a4b5c6d7e'

# Author of this module
Author = 'agent-team'

# Company or vendor of this module
CompanyName = 'agent-team'

# Copyright statement for this module
Copyright = '(c) agent-team. MIT license.'

# Description of the functionality provided by this module
Description = 'Pre-commit hook fail-safe module: BOM encoding contract + backup + permission auto-repair + cross-platform'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-HookContent', 'Write-HookNoBom', 'Write-FileWithBom',
               'Backup-ExistingHook', 'Test-HookUpToDate', 'Set-SourceRepoEnv',
               'Test-SourceRepoEnv', 'Resolve-GitDir', 'Test-HookMarker',
               'Test-HookExecutable', 'Repair-HookPermission',
               'Invoke-SafeHookWrite',
               'Get-HookExitCodeMap', 'Resolve-HookExitCode', 'Invoke-HookWithCapture'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    #SourceOfTruth of this module
    SourceOfTruth = 'scripts/dev/hook_fail_safe.psm1'

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'pre-commit','hook','fail-safe','powershell','tlm','cross-platform'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/nzt47/security-tools/blob/master/packages/tlm-hook-failsafe/LICENSE'

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'v1.1.10: pure validation release (no source changes) to confirm publish-psgallery.yml CI chain stability after v1.1.9 action-gh-release@v3 upgrade. v1.1.9: upgrade softprops/action-gh-release@v2 to @v3 (Node 24 native, eliminate last Node 20 warning). v1.1.8: fix GitHub Release not created (root cause: needs.auto-tag.outputs.tagged not accessible via transitive dependency, fix: explicit needs auto-tag in publish job). v1.1.7: migrate licenseUrl to license type=expression MIT (NuGet 4.9.2+ recommended) + fix GitHub Release if condition. v1.1.6: fix PSGallery license warning by adding licenseUrl to nuspec template. v1.1.5: fix Node 20 deprecation (checkout@v5, upload-artifact@v6) + add LICENSE + enable LicenseUri + fix sync-from-source.ps1 double BOM. v1.1.4: auto-tag publish in same workflow (no cross-workflow trigger). v1.1.3: auto-tag CI/CD full chain with actions:write permission. v1.1.2: auto-tag CI/CD full chain validation. v1.1.1: auto-tag CI/CD validation release. v1.1.0: add exit code resolution layer (Get-HookExitCodeMap, Resolve-HookExitCode, Invoke-HookWithCapture). v1.0.0: initial release, 12 exported functions, sourced from scripts/dev/hook_fail_safe.psm1'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

