#
# Module manifest for tlm-hook-failsafe
#
# Generated by: agent-team
# Generated on: 2026-07-29
#
# 三义校验：
# - 不易：FunctionsToExport 与 hook_fail_safe.psm1 末尾 Export-ModuleMember 一一对应（12 个）
# - �易：CompatiblePSEditions 支持 Desktop (PS 5.1) + Core (PS 7+)
# - 简易：仅必要字段，无嵌套依赖
#

@{
    RootModule           = 'tlm-hook-failsafe.psm1'
    ModuleVersion         = '1.0.0'
    GUID                 = 'b3c4d5e6-f7a8-4b9c-0d1e-2f3a4b5c6d7e'
    Author               = 'agent-team'
    CompanyName          = 'agent-team'
    Copyright            = '(c) agent-team. MIT license.'
    Description          = 'Pre-commit hook fail-safe 核心模块：BOM 编码契约 + 备份 + 权限自动修复 + 跨平台'
    PowerShellVersion    = '5.1'
    CompatiblePSEditions = @('Desktop', 'Core')

    # 不变量：12 个导出函数与源 hook_fail_safe.psm1 末尾 Export-ModuleMember 一一对应
    FunctionsToExport = @(
        'Get-HookContent',
        'Write-HookNoBom',
        'Write-FileWithBom',
        'Backup-ExistingHook',
        'Test-HookUpToDate',
        'Set-SourceRepoEnv',
        'Test-SourceRepoEnv',
        'Resolve-GitDir',
        'Test-HookMarker',
        'Test-HookExecutable',
        'Repair-HookPermission',
        'Invoke-SafeHookWrite'
    )
    VariablesToExport   = @()
    CmdletsToExport     = @()
    AliasesToExport     = @()

    RequiredModules     = @()
    RequiredAssemblies  = @()
    ScriptsToProcess    = @()
    FormatsToProcess    = @()
    TypesToProcess      = @()
    NestedModules       = @()

    HelpInfoURI         = ''

    PrivateData = @{
        PSData = @{
            Tags         = @('pre-commit','hook','fail-safe','powershell','tlm','cross-platform')
            ProjectUri   = ''
            LicenseUri   = ''
            ReleaseNotes = 'v1.0.0: 初始版本，12 个导出函数，源自 scripts/dev/hook_fail_safe.psm1'
            # 不变量标注：真相源路径（供 sync-from-source.ps1 反向校验）
            SourceOfTruth = 'scripts/dev/hook_fail_safe.psm1'
        }
    }
}
