<#
.SYNOPSIS
    Pre-commit Hook Fail-Safe 模块（可复用核心能力）

.DESCRIPTION
    从 sync_precommit_hook.ps1 提取的 fail-safe 核心逻辑，供其他脚本复用。
    三义校验：
    - 不易：hook 阈值 0 写死；hook 无 BOM / PS1 有 BOM 编码契约；已有 hook 必先备份
    - 变易：函数参数化，可被任意脚本 dot-source 或 Import-Module
    - 简易：每个函数单一职责，无外部依赖

    导出函数：
    - Get-HookContent        生成 hook bash 内容（含 marker 行）
    - Write-HookNoBom        写 hook 文件（UTF-8 无 BOM，bash 兼容）
    - Write-FileWithBom      写 PS1 脚本（UTF-8 with BOM，中文兼容）
    - Backup-ExistingHook    备份已有 hook 到时间戳文件
    - Test-HookUpToDate      幂等检测（内容比对）
    - Set-SourceRepoEnv      设置 TLM_HOOK_SOURCE_REPO 环境变量
    - Test-SourceRepoEnv     验证环境变量是否有效
    - Resolve-GitDir        解析 .git 真实路径（兼容 worktree/submodule）
    - Test-HookMarker        检测 hook 是否为本工具生成（含 marker）

.EXAMPLE
    # dot-source 方式复用
    . .\scripts\dev\hook_fail_safe.psm1
    $content = Get-HookContent -SourceRepo "C:\path\to\repo"
    Write-HookNoBom -Path "$repo\.git\hooks\pre-commit" -Content $content

    # Import-Module 方式复用
    Import-Module .\scripts\dev\hook_fail_safe.psm1 -Force
#>

# =================================================================
# 1. hook 内容模板（不易：模板锁定，阈值 0 写死）
# =================================================================
function Get-HookContent {
    <#
    .SYNOPSIS
        生成 pre-commit hook 的 bash 内容
    .DESCRIPTION
        三道 fail-safe 防护：
        1. TLM_HOOK_SOURCE_REPO 未设置 -> exit 1
        2. precheck_docs.ps1 不存在 -> exit 1
        3. powershell 调用失败 -> exit 1
    .PARAMETER SourceRepo
        源仓库根目录路径（写入 marker 行用于审计）
    .OUTPUTS
        [string] hook bash 脚本内容
    #>
    param([string]$SourceRepo)

    $lines = @(
        '#!/bin/bash',
        "# TLM-HOOK v1 source_repo=$SourceRepo",
        '# Auto-generated by scripts/dev/sync_precommit_hook.ps1',
        '# 阻塞模式：失效链接超过阈值时阻止提交（阈值 0 不可绕过）',
        '',
        'echo "[pre-commit] 运行 docs 预检（阻塞模式）..."',
        '# 通过环境变量 TLM_HOOK_SOURCE_REPO 间接寻址源仓库，hook 可复制到任意仓库',
        'if [ -z "$TLM_HOOK_SOURCE_REPO" ]; then',
        '    echo "[pre-commit][ERROR] TLM_HOOK_SOURCE_REPO 未设置，请运行 sync_precommit_hook.ps1" 1>&2',
        '    exit 1',
        'fi',
        '',
        'PS1_PATH="$TLM_HOOK_SOURCE_REPO/scripts/dev/precheck_docs.ps1"',
        'if [ ! -f "$PS1_PATH" ]; then',
        '    echo "[pre-commit][ERROR] 源仓库脚本不存在: $PS1_PATH" 1>&2',
        '    echo "  提示: 检查 TLM_HOOK_SOURCE_REPO 是否指向有效仓库根目录" 1>&2',
        '    exit 1',
        'fi',
        '',
        'powershell -ExecutionPolicy Bypass -File "$PS1_PATH" -SkipChart -BlockMode -AllowBroken 0 -TargetRepo "$(git rev-parse --show-toplevel)"',
        'result=$?',
        'if [ $result -ne 0 ]; then',
        '    echo ""',
        '    echo "[pre-commit] 预检失败，提交被阻止"',
        '    echo "  修复方案: powershell -File \"$TLM_HOOK_SOURCE_REPO/scripts/dev/fix_broken_links.ps1\" -DryRun"',
        '    echo "  临时跳过: git commit --no-verify"',
        '    exit 1',
        'fi',
        'echo "[pre-commit] 预检通过"',
        'exit 0'
    )
    return ($lines -join "`n") + "`n"
}

# =================================================================
# 2. 文件写入：BOM 编码契约（不易）
# =================================================================
function Write-HookNoBom {
    <#
    .SYNOPSIS
        写 hook 文件（UTF-8 无 BOM，bash 兼容）
    .DESCRIPTION
        bash 不识别带 BOM 的 shebang #!/bin/bash，必须无 BOM。
        不使用 Set-Content（PS 5.1 默认加 BOM）。
    #>
    param([string]$Path, [string]$Content)
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function Write-FileWithBom {
    <#
    .SYNOPSIS
        写 PS1 脚本文件（UTF-8 with BOM，PowerShell 5.1 中文兼容）
    .DESCRIPTION
        PS 5.1 在中文系统下默认 GBK 解码，无 BOM 会导致中文乱码。
    #>
    param([string]$Path, [string]$Content)
    $utf8WithBom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8WithBom)
}

# =================================================================
# 3. 备份逻辑（不易：先备份后覆盖）
# =================================================================
function Backup-ExistingHook {
    <#
    .SYNOPSIS
        备份已有 hook 到时间戳文件
    .DESCRIPTION
        - 跳过 pre-commit.bak.* 自身（避免链式备份）
        - 跳过 *.sample（git 自带模板）
        - 同秒重复运行自动追加序号 .1/.2
    .PARAMETER HookPath
        hook 文件路径
    .PARAMETER DryRun
        DryRun 模式下不实际复制
    .OUTPUTS
        [string] 备份文件路径，无需备份时返回 $null
    #>
    param(
        [string]$HookPath,
        [switch]$DryRun
    )
    if (-not (Test-Path $HookPath)) { return $null }

    $fileName = Split-Path $HookPath -Leaf
    if ($fileName -like "pre-commit.bak.*") { return $null }
    if ($fileName -like "*.sample") { return $null }

    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $bakPath = "$HookPath.bak.$timestamp"

    $seq = 1
    while (Test-Path $bakPath) {
        $bakPath = "$HookPath.bak.$timestamp.$seq"
        $seq++
    }

    if (-not $DryRun) {
        Copy-Item -Path $HookPath -Destination $bakPath -Force
    }
    return $bakPath
}

# =================================================================
# 4. 幂等性检测（变易：已是最新则跳过）
# =================================================================
function Test-HookUpToDate {
    <#
    .SYNOPSIS
        检测 hook 是否已是最新版本
    .DESCRIPTION
        内容比对前归一化 CRLF/LF，避免编辑器换行差异误判。
    .OUTPUTS
        [bool] $true 表示已是最新可跳过
    #>
    param([string]$HookPath, [string]$NewContent)
    if (-not (Test-Path $HookPath)) { return $false }
    $current = [System.IO.File]::ReadAllText($HookPath, [System.Text.Encoding]::UTF8)
    $currentNorm = $current -replace "`r`n", "`n"
    $newNorm     = $NewContent -replace "`r`n", "`n"
    return $currentNorm -eq $newNorm
}

# =================================================================
# 5. 环境变量管理（变易：可重指向）
# =================================================================
function Set-SourceRepoEnv {
    <#
    .SYNOPSIS
        设置 TLM_HOOK_SOURCE_REPO 环境变量（User 级 + 当前进程）
    .DESCRIPTION
        - User 级：跨进程持久，不需要管理员权限
        - 当前进程 $env:：保证同会话内立即可用
    .PARAMETER Path
        源仓库根目录路径
    .PARAMETER DryRun
        DryRun 模式下只打印不写入
    #>
    param(
        [string]$Path,
        [switch]$DryRun
    )
    if ($DryRun) {
        Write-Host "  [DryRun] 将设置 User 级 TLM_HOOK_SOURCE_REPO = $Path" -ForegroundColor Yellow
        return
    }
    [System.Environment]::SetEnvironmentVariable('TLM_HOOK_SOURCE_REPO', $Path, 'User')
    $env:TLM_HOOK_SOURCE_REPO = $Path
    Write-Host "  [OK] TLM_HOOK_SOURCE_REPO = $Path (User 级 + 当前进程)" -ForegroundColor Green
}

function Test-SourceRepoEnv {
    <#
    .SYNOPSIS
        验证 TLM_HOOK_SOURCE_REPO 环境变量是否有效
    .DESCRIPTION
        检查：1) 变量已设置 2) 路径存在 3) precheck_docs.ps1 存在
    .OUTPUTS
        [hashtable] @{ Valid = $bool; Value = $string; Error = $string }
    #>
    $result = @{ Valid = $false; Value = $null; Error = $null }
    $envRepo = [System.Environment]::GetEnvironmentVariable('TLM_HOOK_SOURCE_REPO','User')
    $result.Value = $envRepo

    if (-not $envRepo) {
        $result.Error = 'TLM_HOOK_SOURCE_REPO 未设置（请运行 sync_precommit_hook.ps1）'
        return $result
    }
    if (-not (Test-Path $envRepo)) {
        $result.Error = "TLM_HOOK_SOURCE_REPO 指向的路径不存在: $envRepo"
        return $result
    }
    $ps1Path = Join-Path $envRepo "scripts\dev\precheck_docs.ps1"
    if (-not (Test-Path $ps1Path)) {
        $result.Error = "源仓库脚本不存在: $ps1Path"
        return $result
    }
    $result.Valid = $true
    return $result
}

# =================================================================
# 6. .git 路径解析（变易：兼容 worktree/submodule）
# =================================================================
function Resolve-GitDir {
    <#
    .SYNOPSIS
        解析 .git 真实路径
    .DESCRIPTION
        .git 为文件（worktree/submodule）时，解析 gitdir: 指针。
        .git 为目录时，直接返回。
    .OUTPUTS
        [string] .git 真实目录路径，非 git 仓库返回 $null
    #>
    param([string]$RepoPath)
    $gitPath = Join-Path $RepoPath ".git"
    if (-not (Test-Path $gitPath)) { return $null }

    if (Test-Path $gitPath -PathType Leaf) {
        $content = [System.IO.File]::ReadAllText($gitPath, [System.Text.Encoding]::UTF8)
        if ($content -match 'gitdir:\s*(.+)') {
            $gitDir = $Matches[1].Trim()
            if (-not ([System.IO.Path]::IsPathRooted($gitDir))) {
                $gitDir = [System.IO.Path]::GetFullPath((Join-Path $RepoPath $gitDir))
            }
            return $gitDir
        }
        return $null
    }
    return $gitPath
}

# =================================================================
# 7. hook marker 检测（变易：识别本工具生成的 hook）
# =================================================================
function Test-HookMarker {
    <#
    .SYNOPSIS
        检测 hook 是否为本工具生成（含 TLM-HOOK v1 marker）
    .OUTPUTS
        [hashtable] @{ IsOurs = $bool; SourceRepo = $string; Threshold = $string }
    #>
    param([string]$HookPath)
    $result = @{ IsOurs = $false; SourceRepo = $null; Threshold = $null }
    if (-not (Test-Path $HookPath)) { return $result }

    $content = [System.IO.File]::ReadAllText($HookPath, [System.Text.Encoding]::UTF8)
    # 用 [^\r\n]+ 匹配到行尾，避免 $ 在多行模式下的歧义
    if ($content -match 'TLM-HOOK v1 source_repo=([^\r\n]+)') {
        $result.IsOurs = $true
        $result.SourceRepo = $Matches[1].Trim()
    }
    if ($content -match '-AllowBroken\s+(\d+)') {
        $result.Threshold = $Matches[1]
    }
    return $result
}

# 导出所有函数
Export-ModuleMember -Function Get-HookContent, Write-HookNoBom, Write-FileWithBom, Backup-ExistingHook, Test-HookUpToDate, Set-SourceRepoEnv, Test-SourceRepoEnv, Resolve-GitDir, Test-HookMarker
