<#
.SYNOPSIS
    本地开发预检脚本：提交 docs 前生成性能图表 + 验证链接

.DESCRIPTION
    在本地提交 docs/ 变更前运行，预览效果：
    1. 重新生成性能图表（如脚本存在）
    2. 检查 docs/ 中的 Markdown 链接是否有效
    3. 显示待提交文件摘要

    建议集成到 git pre-commit hook，实现提交前自动预览。

.PARAMETER SkipChart
    跳过图表生成（仅检查链接）

.PARAMETER InstallHook
    安装 git pre-commit hook（一次性操作）

.PARAMETER BlockMode
    阻塞模式：发现失效链接时返回非 0 退出码，阻止 git commit。
    用于 pre-commit hook 强制校验。

.PARAMETER AllowBroken
    允许的失效链接数阈值（默认 0）。超过此值才阻塞。
    用于渐进式修复：先设为 98，逐次降低到 0。

.EXAMPLE
    .\scripts\dev\precheck_docs.ps1
    .\scripts\dev\precheck_docs.ps1 -SkipChart
    .\scripts\dev\precheck_docs.ps1 -InstallHook
    .\scripts\dev\precheck_docs.ps1 -BlockMode -AllowBroken 98
#>
param(
    [switch]$SkipChart,
    [switch]$InstallHook,
    [switch]$BlockMode,
    [int]$AllowBroken = 0,
    [string]$TargetRepo,
    # 字节级调试模式（即 -Verbose 模式）：PS 5.1 的 -File 调用会把 -Verbose 作为保留参数名
    # 处理、不绑定到显式 switch，因此用 -BomDiag 实现（hook 经 TLM_HOOK_VERBOSE=1 透传）
    [switch]$BomDiag
)

$ErrorActionPreference = "Continue"

# -BomDiag → 提升 Verbose 流偏好，后续 Write-Verbose 均生效
if ($BomDiag) {
    $VerbosePreference = 'Continue'
}

# ── 字节级 BOM 诊断（-Verbose 时用于定位 BOM 相关边缘问题） ──
function Test-FileBomSignature {
    <#
    .SYNOPSIS
        检测文件开头的 UTF-8 BOM 状态（None / Single / Stacked）
    .DESCRIPTION
        - None:   无 BOM（bash hook / python 约定）
        - Single: 单 BOM（PowerShell 5.1 中文兼容，期望状态）
        - Stacked: 叠加 BOM（≥2 个连续 EF BB BF），会破坏 <# 块注释，是历史事故根因
    .OUTPUTS
        [PSCustomObject] @{ State; BomCount; HeadHex }
    #>
    param([string]$Path)
    $bytes = [System.IO.File]::ReadAllBytes($Path)
    $count = 0
    $i = 0
    while ($i + 2 -lt $bytes.Length -and $bytes[$i] -eq 0xEF -and $bytes[$i + 1] -eq 0xBB -and $bytes[$i + 2] -eq 0xBF) {
        $count++
        $i += 3
    }
    $state = if ($count -ge 2) { 'Stacked' } elseif ($count -eq 1) { 'Single' } else { 'None' }
    $last = [Math]::Min(8, $bytes.Length - 1)
    $hex = ($bytes[0..$last] | ForEach-Object { $_.ToString('X2') }) -join ' '
    return [PSCustomObject]@{ State = $state; BomCount = $count; HeadHex = $hex }
}
$ProjectRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
# 若指定 -TargetRepo（被 sync_precommit_hook.ps1 部署的 hook 调用），切换到目标仓库根目录；
# 否则保持原行为（cd 到脚本所在源仓库根目录）
if ($TargetRepo) {
    if (-not (Test-Path $TargetRepo)) {
        Write-Host "[ERROR] -TargetRepo 指定的路径不存在: $TargetRepo" -ForegroundColor Red
        exit 1
    }
    Set-Location $TargetRepo
} else {
    Set-Location $ProjectRoot
}

Write-Host "=== 本地开发预检 ===" -ForegroundColor Cyan

# ── 安装 pre-commit hook 模式 ──
if ($InstallHook) {
    Write-Host "[安装] 配置 git pre-commit hook..." -ForegroundColor Yellow
    $hookPath = ".git/hooks/pre-commit"
    $hookLines = @(
        '#!/bin/bash',
        '# Auto-generated by scripts/dev/precheck_docs.ps1',
        '# 阻塞模式：失效链接超过阈值时阻止提交',
        '',
        'echo "[pre-commit] 运行 docs 预检（阻塞模式）..."',
        'powershell -ExecutionPolicy Bypass -File scripts/dev/precheck_docs.ps1 -SkipChart -BlockMode -AllowBroken 0',
        'result=$?',
        'if [ $result -ne 0 ]; then',
        '    echo ""',
        '    echo "[pre-commit] 预检失败，提交被阻止"',
        '    echo "  修复方案: powershell -File scripts/dev/fix_broken_links.ps1 -DryRun"',
        '    echo "  临时跳过: git commit --no-verify"',
        '    exit 1',
        'fi',
        'echo "[pre-commit] 预检通过"',
        'exit 0'
    )
    $hookContent = $hookLines -join "`n"
    try {
        Set-Content -Path $hookPath -Value $hookContent -Encoding utf8 -ErrorAction Stop
        Write-Host "[OK] pre-commit hook 已安装到 $hookPath" -ForegroundColor Green
        Write-Host "  策略: 阻塞模式（失效链接超过阈值时阻止提交）" -ForegroundColor Yellow
        Write-Host "  可手动跳过: git commit --no-verify" -ForegroundColor Gray
    } catch {
        Write-Host "[!] 自动安装被拦截（沙盒保护 .git/ 目录）" -ForegroundColor Yellow
        Write-Host "  请手动创建 .git/hooks/pre-commit 文件，内容如下:" -ForegroundColor Gray
        Write-Host "  ----"
        Write-Host $hookContent -ForegroundColor Gray
        Write-Host "  ----"
        Write-Host "  或直接手动调用: .\scripts\dev\precheck_docs.ps1 -SkipChart" -ForegroundColor Gray
    }
    exit 0
}

# ── 步骤 1: 生成性能图表（可选） ──
if (-not $SkipChart) {
    Write-Host "`n[1/3] 生成性能图表..." -ForegroundColor Yellow
    $chartScript = Join-Path $ProjectRoot "scripts\gen_tlm_perf_chart.py"
    if (Test-Path $chartScript) {
        $env:PYTHONIOENCODING = "utf-8"
        python $chartScript 2>&1 | Select-Object -Last 3
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  [OK] 性能图表已生成" -ForegroundColor Green
        } else {
            Write-Host "  [WARN] 图表生成失败（不影响提交）" -ForegroundColor Yellow
        }
    } else {
        Write-Host "  [SKIP] 未找到图表生成脚本" -ForegroundColor Gray
    }
} else {
    Write-Host "`n[1/3] 跳过图表生成（-SkipChart）" -ForegroundColor Gray
}

# ── 步骤 2: 检查 Markdown 链接 ──
Write-Host "`n[2/3] 检查 docs/ Markdown 链接..." -ForegroundColor Yellow
$mdFiles = Get-ChildItem -Path docs -Filter "*.md" -Recurse -ErrorAction SilentlyContinue
$totalLinks = 0
$brokenLinks = 0
# -Verbose 时收集 BOM 异常文件，拦截失败时输出字节级诊断
$bomIssues = @()

foreach ($file in $mdFiles) {
    # 用 .NET API + UTF8 显式编码读取，避免 PowerShell 5.1 默认 GBK 解码中文导致路径乱码
    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    # -Verbose: 检测 Markdown 文件自身的 BOM 状态（叠加 BOM 会破坏文档解析/锚点匹配）
    if ($VerbosePreference -eq 'Continue') {
        $bom = Test-FileBomSignature -Path $file.FullName
        if ($bom.State -eq 'Stacked') {
            Write-Verbose "  [BOM] 叠加 BOM: $($file.FullName) (BOM x$($bom.BomCount), head: $($bom.HeadHex))"
            $bomIssues += $file.FullName
        }
    }
    # 匹配 [text](path) 格式的相对链接
    $links = [regex]::Matches($content, '\[([^\]]+)\]\(([^)]+)\)')
    foreach ($link in $links) {
        $linkPath = $link.Groups[2].Value
        $linkText = $link.Groups[1].Value
        # 跳过 http/https/mailto/file:///绝对路径/锚点链接
        if ($linkPath -match '^(https?|mailto:|file:///|#|/)') { continue }
        $totalLinks++
        # 【不易】合法相对链接可带 #锚点（如 ./guide.md#四、告警规则），
        # Path::Combine + File.Exists 无法解析锚点后缀，必须先剥离，
        # 仅校验文件部分（与 fix_broken_links.ps1 类型 9 逻辑保持一致）
        $anchorSuffix = ''
        if ($linkPath -match '^([^#]+)#') {
            $anchorSuffix = $linkPath.Substring($Matches[1].Length)
            $linkPath = $Matches[1]
        }
        # 归一化 ./ 前缀，避免 Combine 拼接出「目录\./文件」混合分隔符
        $linkPath = $linkPath -replace '^\./', ''
        # 解析相对路径（.NET API 正确处理 Unicode 字符）
        $fullPath = [System.IO.Path]::Combine($file.DirectoryName, $linkPath)
        if (-not ([System.IO.File]::Exists($fullPath) -or [System.IO.Directory]::Exists($fullPath))) {
            Write-Host "  [BROKEN] $($file.Name): $linkPath" -ForegroundColor Red
            if ($VerbosePreference -eq 'Continue') {
                # 字节级诊断：链接原文 / 锚点剥离 / 路径解析全过程
                Write-Verbose "    [DIAG] 链接原文: [$linkText]($($link.Groups[2].Value))"
                Write-Verbose "    [DIAG] 剥离锚点: 后缀=$anchorSuffix 文件部分=$linkPath"
                Write-Verbose "    [DIAG] 解析路径: $fullPath"
                Write-Verbose "    [DIAG] 存在性:   File=$(Test-Path $fullPath -PathType Leaf) Dir=$(Test-Path $fullPath -PathType Container)"
                $fileBom = Test-FileBomSignature -Path $file.FullName
                Write-Verbose "    [DIAG] 宿主文件 BOM: $($fileBom.State) (BOM x$($fileBom.BomCount), head: $($fileBom.HeadHex))"
                if ($fullPath -match '\.(ps1|psm1)$' -and (Test-Path $fullPath)) {
                    $targetBom = Test-FileBomSignature -Path $fullPath
                    Write-Verbose "    [DIAG] 目标脚本 BOM: $($targetBom.State) (BOM x$($targetBom.BomCount), head: $($targetBom.HeadHex))"
                }
            }
            $brokenLinks++
        }
    }
}
Write-Host "  [OK] 检查 $($mdFiles.Count) 个文件，$totalLinks 个链接，$brokenLinks 个失效" -ForegroundColor $(if ($brokenLinks -eq 0) {'Green'} else {'Red'})

# ── 步骤 3: 待提交文件摘要 ──
Write-Host "`n[3/3] 待提交文件摘要..." -ForegroundColor Yellow
$staged = git diff --cached --name-only --diff-filter=ACM 2>&1
$unstagedDocs = git diff --name-only -- docs/ 2>&1

if ($staged) {
    Write-Host "  已暂存文件 ($($staged.Count)):"
    $staged | Select-Object -First 10 | ForEach-Object { Write-Host "    + $_" -ForegroundColor Green }
    if ($staged.Count -gt 10) {
        Write-Host "    ... 共 $($staged.Count) 个" -ForegroundColor Gray
    }
}

if ($unstagedDocs) {
    Write-Host "  docs/ 未暂存变更 ($($unstagedDocs.Count)):"
    $unstagedDocs | ForEach-Object { Write-Host "    M $_" -ForegroundColor Yellow }
    Write-Host "  提示: 使用 git add docs/ 暂存" -ForegroundColor Gray
}

if (-not $staged -and -not $unstagedDocs) {
    Write-Host "  [INFO] 无待提交变更" -ForegroundColor Gray
}

# ── 总结 ──
Write-Host "`n=== 预检完成 ===" -ForegroundColor Cyan
if ($brokenLinks -gt 0) {
    Write-Host "[!] 发现 $brokenLinks 个失效链接" -ForegroundColor Red
} else {
    Write-Host "[OK] 预检通过" -ForegroundColor Green
}
Write-Host "  提交: git commit -m 'docs: 更新文档'"
Write-Host "  推送: git push origin master（自动触发 Pages 部署）"

# ── 阻塞模式：根据失效链接数决定退出码 ──
if ($BlockMode) {
    if ($brokenLinks -gt $AllowBroken) {
        Write-Host ""
        Write-Host "[BLOCK] 阻塞模式：失效链接 $brokenLinks > 阈值 $AllowBroken" -ForegroundColor Red
        Write-Host "  修复方案: .\scripts\dev\fix_broken_links.ps1 -DryRun" -ForegroundColor Yellow
        Write-Host "  临时跳过: git commit --no-verify" -ForegroundColor Yellow
        Write-Host "  调整阈值: -AllowBroken $brokenLinks（渐进式修复）" -ForegroundColor Yellow
        if ($VerbosePreference -eq 'Continue') {
            # 字节级诊断汇总：定位 BOM 相关边缘问题（叠加 BOM 会破坏解析）
            Write-Verbose ""
            Write-Verbose "=== 字节级调试诊断 ==="
            if ($bomIssues.Count -gt 0) {
                Write-Verbose "  [BOM] 发现 $($bomIssues.Count) 个叠加 BOM 的 Markdown 文件（EF BB BF 连续出现 ≥2 次）:"
                foreach ($bomFile in $bomIssues) {
                    $b = Test-FileBomSignature -Path $bomFile
                    Write-Verbose "    - $bomFile"
                    Write-Verbose "      head: $($b.HeadHex)  (BOM x$($b.BomCount))"
                }
                Write-Verbose "  修复: 对 .ps1/.psm1 用单 BOM（TrimStart FEFF + UTF8Encoding(true) 写回）；对 .md 建议去 BOM"
            } else {
                Write-Verbose "  [BOM] 未检测到叠加 BOM 的 Markdown 文件（如需检查 .ps1/.psm1 请直接扫描 scripts/）"
            }
            Write-Verbose "  提示: 叠加 BOM 是 <# 块注释解析失败 / 中文乱码的常见根因，详见 docs/ci_guidelines/precommit_hook_bom_incident_report.md"
        }
        exit 1
    } else {
        Write-Host ""
        Write-Host "[PASS] 阻塞模式：失效链接 $brokenLinks <= 阈值 $AllowBroken" -ForegroundColor Green
        exit 0
    }
}
