<#
.SYNOPSIS
    本地开发预检脚本：提交 docs 前生成性能图表 + 验证链接

.DESCRIPTION
    在本地提交 docs/ 变更前运行，预览效果：
    1. 重新生成性能图表（如脚本存在）
    2. 检查 docs/ 中的 Markdown 链接是否有效
    3. 显示待提交文件摘要

    建议集成到 git pre-commit hook，实现提交前自动预览。

.PARAMETER SkipChart
    跳过图表生成（仅检查链接）

.PARAMETER InstallHook
    安装 git pre-commit hook（一次性操作）

.EXAMPLE
    .\scripts\dev\precheck_docs.ps1
    .\scripts\dev\precheck_docs.ps1 -SkipChart
    .\scripts\dev\precheck_docs.ps1 -InstallHook
#>
[CmdletBinding()]
param(
    [switch]$SkipChart,
    [switch]$InstallHook
)

$ErrorActionPreference = "Continue"
$ProjectRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
Set-Location $ProjectRoot

Write-Host "=== 本地开发预检 ===" -ForegroundColor Cyan

# ── 安装 pre-commit hook 模式 ──
if ($InstallHook) {
    Write-Host "[安装] 配置 git pre-commit hook..." -ForegroundColor Yellow
    $hookPath = ".git/hooks/pre-commit"
    $hookContent = @"
#!/bin/bash
# Auto-generated by scripts/dev/precheck_docs.ps1
# Run docs pre-check before commit (non-blocking, preview only)

echo "[pre-commit] 运行 docs 预检（非阻塞）..."
powershell -ExecutionPolicy Bypass -File scripts/dev/precheck_docs.ps1 -SkipChart
if [ `$? -ne 0 ]; then
    echo "[pre-commit] 预检发现警告，但不阻塞提交"
fi
exit 0  # 始终放行，仅作预览
"@
    Set-Content -Path $hookPath -Value $hookContent -Encoding utf8
    # 设置可执行权限（Git Bash 环境）
    if ($IsLinux -or $IsMacOS) {
        chmod +x $hookPath 2>$null
    }
    Write-Host "[OK] pre-commit hook 已安装到 $hookPath" -ForegroundColor Green
    Write-Host "  策略: 非阻塞预览（不阻止提交）"
    Write-Host "  可手动跳过: git commit --no-verify"
    exit 0
}

# ── 步骤 1: 生成性能图表（可选） ──
if (-not $SkipChart) {
    Write-Host "`n[1/3] 生成性能图表..." -ForegroundColor Yellow
    $chartScript = Join-Path $ProjectRoot "scripts\gen_tlm_perf_chart.py"
    if (Test-Path $chartScript) {
        $env:PYTHONIOENCODING = "utf-8"
        python $chartScript 2>&1 | Select-Object -Last 3
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  [OK] 性能图表已生成" -ForegroundColor Green
        } else {
            Write-Host "  [WARN] 图表生成失败（不影响提交）" -ForegroundColor Yellow
        }
    } else {
        Write-Host "  [SKIP] 未找到图表生成脚本" -ForegroundColor Gray
    }
} else {
    Write-Host "`n[1/3] 跳过图表生成（-SkipChart）" -ForegroundColor Gray
}

# ── 步骤 2: 检查 Markdown 链接 ──
Write-Host "`n[2/3] 检查 docs/ Markdown 链接..." -ForegroundColor Yellow
$mdFiles = Get-ChildItem -Path docs -Filter "*.md" -Recurse -ErrorAction SilentlyContinue
$totalLinks = 0
$brokenLinks = 0

foreach ($file in $mdFiles) {
    $content = Get-Content $file.FullName -Raw
    # 匹配 [text](path) 格式的相对链接
    $links = [regex]::Matches($content, '\[([^\]]+)\]\(([^)]+)\)')
    foreach ($link in $links) {
        $linkPath = $link.Groups[2].Value
        # 跳过 http/https/锚点链接
        if ($linkPath -match '^(https?|mailto:|#|/)') { continue }
        $totalLinks++
        # 解析相对路径
        $fullPath = Join-Path $file.DirectoryName $linkPath
        if (-not (Test-Path $fullPath)) {
            Write-Host "  [BROKEN] $($file.Name): $linkPath" -ForegroundColor Red
            $brokenLinks++
        }
    }
}
Write-Host "  [OK] 检查 $($mdFiles.Count) 个文件，$totalLinks 个链接，$brokenLinks 个失效" -ForegroundColor $(if ($brokenLinks -eq 0) {'Green'} else {'Red'})

# ── 步骤 3: 待提交文件摘要 ──
Write-Host "`n[3/3] 待提交文件摘要..." -ForegroundColor Yellow
$staged = git diff --cached --name-only --diff-filter=ACM 2>&1
$unstagedDocs = git diff --name-only -- docs/ 2>&1

if ($staged) {
    Write-Host "  已暂存文件 ($($staged.Count)):"
    $staged | Select-Object -First 10 | ForEach-Object { Write-Host "    + $_" -ForegroundColor Green }
    if ($staged.Count -gt 10) {
        Write-Host "    ... 共 $($staged.Count) 个" -ForegroundColor Gray
    }
}

if ($unstagedDocs) {
    Write-Host "  docs/ 未暂存变更 ($($unstagedDocs.Count)):"
    $unstagedDocs | ForEach-Object { Write-Host "    M $_" -ForegroundColor Yellow }
    Write-Host "  提示: 使用 git add docs/ 暂存" -ForegroundColor Gray
}

if (-not $staged -and -not $unstagedDocs) {
    Write-Host "  [INFO] 无待提交变更" -ForegroundColor Gray
}

# ── 总结 ──
Write-Host "`n=== 预检完成 ===" -ForegroundColor Cyan
if ($brokenLinks -gt 0) {
    Write-Host "[!] 发现 $brokenLinks 个失效链接" -ForegroundColor Red
} else {
    Write-Host "[OK] 预检通过" -ForegroundColor Green
}
Write-Host "  提交: git commit -m 'docs: 更新文档'"
Write-Host "  推送: git push origin master（自动触发 Pages 部署）"
