<#
.SYNOPSIS
    pre-commit hook 自动化部署与同步工具

.DESCRIPTION
    三义校验：
    - 不易：备份已有 hook 后覆盖；hook 阈值 0 不可绕过；hook 无 BOM / PS1 有 BOM
    - 变易：支持 install/sync/status/dryrun 多模式正交组合
    - 简易：单脚本一键运行；输出自解释

    三道 fail-safe 防护（hook 内）：
    1. TLM_HOOK_SOURCE_REPO 未设置 -> exit 1
    2. precheck_docs.ps1 不存在 -> exit 1
    3. powershell 调用失败 -> exit 1

.PARAMETER Install
    安装到指定目标仓库路径（缺省：当前仓库）

.PARAMETER Sync
    扫描 -ScanRoot 下所有 git 仓库批量同步

.PARAMETER ScanRoot
    sync 模式扫描根目录（默认 c:\Users\Administrator）

.PARAMETER Status
    显示所有已安装仓库的状态汇总

.PARAMETER DryRun
    预览模式：仅打印将要执行的动作，不写入、不备份、不改环境变量

.PARAMETER SourceRepo
    源仓库路径（默认自动检测为 $PSScriptRoot\..\..）
    写入 TLM_HOOK_SOURCE_REPO 环境变量（User 级 + 当前进程）

.EXAMPLE
    .\scripts\dev\sync_precommit_hook.ps1
    .\scripts\dev\sync_precommit_hook.ps1 -Install D:\code\other-repo
    .\scripts\dev\sync_precommit_hook.ps1 -Sync -ScanRoot D:\code
    .\scripts\dev\sync_precommit_hook.ps1 -Status
    .\scripts\dev\sync_precommit_hook.ps1 -Sync -DryRun
#>
[CmdletBinding()]
param(
    [switch]$Sync,
    [string]$Install,
    [switch]$Status,
    [switch]$DryRun,
    [string]$ScanRoot = "c:\Users\Administrator",
    [string]$SourceRepo
)

# Continue mode: avoid aborting on git stderr warnings (LF/CRLF etc.)
$ErrorActionPreference = "Continue"

# --- 全局状态 ---
$script:ProjectRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
$script:SourceRepo  = if ($SourceRepo) { $SourceRepo } else { $script:ProjectRoot }
$script:Results      = @()   # 收集所有目标的状态，供汇总表使用

# --- 辅助：步骤标题 ---
function Write-Step {
    param([int]$Index, [int]$Total, [string]$Message)
    Write-Host "`n[$Index/$Total] $Message" -ForegroundColor Yellow
}

# --- 1. hook 内容模板（不易：模板锁定，阈值 0 写死） ---
function Get-HookContent {
    # marker 行用于幂等检测与 -Status 识别（含源仓库路径，便于审计）
    # bash 单引号内 $ 不会被展开，故 $TLM_HOOK_SOURCE_REPO 字面量保留
    $lines = @(
        '#!/bin/bash',
        "# TLM-HOOK v1 source_repo=$($script:SourceRepo)",
        '# Auto-generated by scripts/dev/sync_precommit_hook.ps1',
        '# 阻塞模式：失效链接超过阈值时阻止提交（阈值 0 不可绕过）',
        '',
        'echo "[pre-commit] 运行 docs 预检（阻塞模式）..."',
        '# 通过环境变量 TLM_HOOK_SOURCE_REPO 间接寻址源仓库，hook 可复制到任意仓库',
        'if [ -z "$TLM_HOOK_SOURCE_REPO" ]; then',
        '    echo "[pre-commit][ERROR] TLM_HOOK_SOURCE_REPO 未设置，请运行 sync_precommit_hook.ps1" 1>&2',
        '    exit 1',
        'fi',
        '',
        'PS1_PATH="$TLM_HOOK_SOURCE_REPO/scripts/dev/precheck_docs.ps1"',
        'if [ ! -f "$PS1_PATH" ]; then',
        '    echo "[pre-commit][ERROR] 源仓库脚本不存在: $PS1_PATH" 1>&2',
        '    echo "  提示: 检查 TLM_HOOK_SOURCE_REPO 是否指向有效仓库根目录" 1>&2',
        '    exit 1',
        'fi',
        '',
        'powershell -ExecutionPolicy Bypass -File "$PS1_PATH" -SkipChart -BlockMode -AllowBroken 0 -TargetRepo "$(git rev-parse --show-toplevel)"',
        'result=$?',
        'if [ $result -ne 0 ]; then',
        '    echo ""',
        '    echo "[pre-commit] 预检失败，提交被阻止"',
        '    echo "  修复方案: powershell -File \"$TLM_HOOK_SOURCE_REPO/scripts/dev/fix_broken_links.ps1\" -DryRun"',
        '    echo "  临时跳过: git commit --no-verify"',
        '    exit 1',
        'fi',
        'echo "[pre-commit] 预检通过"',
        'exit 0'
    )
    return ($lines -join "`n") + "`n"
}

# --- 2. 写 hook 文件：必须无 BOM（bash 兼容） ---
function Write-HookNoBom {
    param([string]$Path, [string]$Content)
    # UTF8Encoding($false) = 无 BOM；不用 Set-Content（PS 5.1 默认加 BOM）
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

# --- 3. 备份已有 hook（不易：先备份后覆盖） ---
function Backup-ExistingHook {
    param([string]$HookPath)
    if (-not (Test-Path $HookPath)) { return $null }

    $fileName = Split-Path $HookPath -Leaf
    # 跳过已经是本工具生成的备份文件（避免链式备份）
    if ($fileName -like "pre-commit.bak.*") { return $null }
    # 跳过 git 自带 sample
    if ($fileName -like "*.sample") { return $null }

    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $bakPath = "$HookPath.bak.$timestamp"

    # 幂等保护：同一秒内重复运行会冲突，自动加序号
    $seq = 1
    while (Test-Path $bakPath) {
        $bakPath = "$HookPath.bak.$timestamp.$seq"
        $seq++
    }

    if (-not $DryRun) {
        Copy-Item -Path $HookPath -Destination $bakPath -Force
    }
    return $bakPath
}

# --- 4. 幂等性检测（变易：已是最新则跳过） ---
function Test-HookUpToDate {
    param([string]$HookPath, [string]$NewContent)
    if (-not (Test-Path $HookPath)) { return $false }
    $current = [System.IO.File]::ReadAllText($HookPath, [System.Text.Encoding]::UTF8)
    # 归一化 CRLF/LF 后比对，避免编辑器换行差异误判
    $currentNorm = $current -replace "`r`n", "`n"
    $newNorm     = $NewContent -replace "`r`n", "`n"
    return $currentNorm -eq $newNorm
}

# --- 5. 设置环境变量（变易：可重指向） ---
function Set-SourceRepoEnv {
    param([string]$Path)
    if ($DryRun) {
        Write-Host "  [DryRun] 将设置 User 级 TLM_HOOK_SOURCE_REPO = $Path" -ForegroundColor Yellow
        return
    }
    # User 级：跨进程持久；不需要管理员权限
    [System.Environment]::SetEnvironmentVariable('TLM_HOOK_SOURCE_REPO', $Path, 'User')
    # 同步注入当前进程，否则当前 shell 内 hook 测试仍读不到
    $env:TLM_HOOK_SOURCE_REPO = $Path
    Write-Host "  [OK] TLM_HOOK_SOURCE_REPO = $Path (User 级 + 当前进程)" -ForegroundColor Green
}

# --- 6. 扫描根目录下所有 git 仓库 ---
function Find-GitRepos {
    param([string]$Root)

    if (-not (Test-Path $Root)) {
        Write-Host "[ERROR] 扫描根目录不存在: $Root" -ForegroundColor Red
        exit 1
    }

    # 跳过列表（不易：避免误改依赖包/虚拟环境/系统目录中的 git 仓库）
    $skipNames = @(
        'node_modules', '.venv', 'venv', '__pycache__', '.pytest_cache',
        '.cache', 'site-packages', 'dist', 'build', 'target',
        '.git', '.hg', '.svn',
        'AppData',
        '.vscode', '.vscode-shared',
        'OneDrive'
    )

    $found = @()
    # 只扫一层子目录（用户家目录下嵌套深的一般不是开发仓库）
    Get-ChildItem -Path $Root -Directory -Force -ErrorAction SilentlyContinue | ForEach-Object {
        $dir = $_
        if ($skipNames -contains $dir.Name) { return }

        # 命中 .git 目录/文件 -> 父目录是 git 仓库
        $gitChild = Join-Path $dir.FullName ".git"
        if (Test-Path $gitChild) {
            $found += $dir.FullName
            # 不再深入子目录（剪枝）
            return
        }
    }

    return $found
}

# --- 7. 解析 .git 真实路径（兼容 worktree/submodule） ---
function Resolve-GitDir {
    param([string]$RepoPath)

    $gitPath = Join-Path $RepoPath ".git"
    if (-not (Test-Path $gitPath)) { return $null }

    # .git 为文件（worktree/submodule）时，解析 gitdir: 指针
    if (Test-Path $gitPath -PathType Leaf) {
        $content = [System.IO.File]::ReadAllText($gitPath, [System.Text.Encoding]::UTF8)
        if ($content -match 'gitdir:\s*(.+)') {
            $gitDir = $Matches[1].Trim()
            if (-not ([System.IO.Path]::IsPathRooted($gitDir))) {
                $gitDir = [System.IO.Path]::GetFullPath((Join-Path $RepoPath $gitDir))
            }
            return $gitDir
        }
        return $null
    }

    # .git 为目录
    return $gitPath
}

# --- 8. 单仓库部署编排（简易：编排清晰） ---
function Install-HookToRepo {
    param([string]$RepoPath, [int]$Index, [int]$Total)

    $repoName = Split-Path $RepoPath -Leaf
    $gitDir = Resolve-GitDir -RepoPath $RepoPath

    if (-not $gitDir) {
        Write-Host "  [$Index/$Total] SKIP $repoPath (非 git 仓库)" -ForegroundColor Gray
        $script:Results += [PSCustomObject]@{
            Repo = $repoName; Status = 'SKIP'; Backup = '-'; Threshold = '-'
        }
        return
    }

    $hookPath = Join-Path $gitDir "hooks\pre-commit"
    $hooksDir = Split-Path $hookPath -Parent
    if (-not (Test-Path $hooksDir)) {
        if (-not $DryRun) {
            New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
        }
    }

    $newContent = Get-HookContent

    # 幂等检测：已是最新则跳过
    if (Test-HookUpToDate -HookPath $hookPath -NewContent $newContent) {
        Write-Host "  [$Index/$Total] OK   $repoName (已是最新，跳过)" -ForegroundColor DarkGray
        $script:Results += [PSCustomObject]@{
            Repo = $repoName; Status = 'OK_LATEST'; Backup = '-'; Threshold = '0'
        }
        return
    }

    # 备份已有 hook
    $bakPath = Backup-ExistingHook -HookPath $hookPath
    if ($bakPath) {
        Write-Host "  [$Index/$Total] BAK  $repoName -> $(Split-Path $bakPath -Leaf)" -ForegroundColor Yellow
    }

    if ($DryRun) {
        Write-Host "  [$Index/$Total] DRY  $repoName (将写入 hook，阈值 0)" -ForegroundColor Cyan
        $script:Results += [PSCustomObject]@{
            Repo = $repoName; Status = 'DRYRUN'; Backup = $(if ($bakPath) { Split-Path $bakPath -Leaf } else { '-' }); Threshold = '0'
        }
        return
    }

    # 写入 hook（无 BOM）
    Write-HookNoBom -Path $hookPath -Content $newContent

    # bash 语法检查已移除：Windows 下 git-bash 路径转换会导致误报。
    # hook 语法由 git commit 时实际调用 bash 验证；若语法错误 hook 会 exit 1 阻塞提交（fail-safe）。

    Write-Host "  [$Index/$Total] DONE $repoName (hook 已部署，阈值 0)" -ForegroundColor Green
    $script:Results += [PSCustomObject]@{
        Repo = $repoName; Status = 'INSTALLED'; Backup = $(if ($bakPath) { Split-Path $bakPath -Leaf } else { '-' }); Threshold = '0'
    }
}

# --- 9. 汇总表 ---
function Show-SummaryTable {
    Write-Host ""
    Write-Host "=== 部署汇总 ===" -ForegroundColor Cyan
    if ($script:Results.Count -eq 0) {
        Write-Host "  (无目标)" -ForegroundColor Gray
        return
    }
    $script:Results | Format-Table -AutoSize -Property Repo, Status, Backup, Threshold

    $okCount     = @($script:Results | Where-Object { $_.Status -eq 'INSTALLED' -or $_.Status -eq 'OK_LATEST' }).Count
    $skipCount   = @($script:Results | Where-Object { $_.Status -eq 'SKIP' }).Count
    $dryrunCount = @($script:Results | Where-Object { $_.Status -eq 'DRYRUN' }).Count
    $color = if ($skipCount -eq 0 -and $dryrunCount -eq 0) { 'Green' } else { 'Yellow' }
    Write-Host "  成功: $okCount | 跳过: $skipCount | DryRun: $dryrunCount" -ForegroundColor $color
}

# --- 10. 状态查询模式 ---
function Show-Status {
    Write-Host "=== Hook 安装状态 ===" -ForegroundColor Cyan

    $envRepo = [System.Environment]::GetEnvironmentVariable('TLM_HOOK_SOURCE_REPO','User')
    $envColor = if ($envRepo) { 'Green' } else { 'Red' }
    Write-Host "  TLM_HOOK_SOURCE_REPO (User) = $(if ($envRepo) { $envRepo } else { '<未设置>' })" -ForegroundColor $envColor

    if (-not $envRepo) {
        Write-Host "  [HINT] 运行一次 install/sync 后此变量才会被设置" -ForegroundColor Gray
        return
    }

    # 扫描根目录下所有 git 仓库，检测 hook 状态
    Write-Host "`n[1/2] 扫描 $ScanRoot 下的 git 仓库..." -ForegroundColor Yellow
    $targets = Find-GitRepos -Root $ScanRoot
    Write-Host "  [OK] 发现 $($targets.Count) 个 git 仓库" -ForegroundColor Green

    Write-Host "`n[2/2] 检测 hook 状态..." -ForegroundColor Yellow
    foreach ($t in $targets) {
        $gitDir = Resolve-GitDir -RepoPath $t
        $repoName = Split-Path $t -Leaf

        if (-not $gitDir) {
            $script:Results += [PSCustomObject]@{ Repo = $repoName; Status = 'SKIP'; Backup = '-'; Threshold = '-' }
            continue
        }

        $hookPath = Join-Path $gitDir "hooks\pre-commit"
        if (-not (Test-Path $hookPath)) {
            $script:Results += [PSCustomObject]@{ Repo = $repoName; Status = 'NOT_INSTALLED'; Backup = '-'; Threshold = '-' }
            continue
        }

        $hookContent = [System.IO.File]::ReadAllText($hookPath, [System.Text.Encoding]::UTF8)
        $hasMarker = $hookContent -match 'TLM-HOOK v1'
        $threshold = if ($hookContent -match '-AllowBroken\s+(\d+)') { $Matches[1] } else { '?' }

        # 检测是否有备份
        $hooksDir = Split-Path $hookPath -Parent
        $bakFiles = Get-ChildItem $hooksDir -Filter 'pre-commit.bak.*' -ErrorAction SilentlyContinue
        $hasBackup = if ($bakFiles) { "YES ($($bakFiles.Count))" } else { '-' }

        $status = if ($hasMarker) { 'INSTALLED' } else { 'OTHER_HOOK' }
        $script:Results += [PSCustomObject]@{
            Repo = $repoName; Status = $status; Backup = $hasBackup; Threshold = $threshold
        }
    }
    Show-SummaryTable
}

# --- 入口分发 ---
Write-Host "=== Pre-commit Hook 自动化部署 ===" -ForegroundColor Cyan
Write-Host "  模式: $(if ($Status) { 'status' } elseif ($Sync) { "sync (root=$ScanRoot)" } elseif ($Install) { "install -> $Install" } else { 'install (current repo)' })"
Write-Host "  DryRun: $DryRun"
Write-Host "  SourceRepo: $($script:SourceRepo)"

if ($Status) {
    Show-Status
    exit 0
}

# --- sync / install 模式 ---
if ($Sync) {
    Write-Step 1 3 "扫描 $ScanRoot 下的 git 仓库..."
    $targets = Find-GitRepos -Root $ScanRoot
    Write-Host "  [OK] 发现 $($targets.Count) 个 git 仓库" -ForegroundColor Green
    if ($targets.Count -eq 0) {
        Write-Host "  [INFO] 未发现 git 仓库，退出" -ForegroundColor Gray
        exit 0
    }
} elseif ($Install) {
    $targets = @($Install)
} else {
    # 默认：安装到当前仓库
    $targets = @($script:ProjectRoot)
}

Write-Step 2 3 "设置环境变量 TLM_HOOK_SOURCE_REPO..."
Set-SourceRepoEnv -Path $script:SourceRepo

Write-Step 3 3 "部署 hook 到 $($targets.Count) 个仓库..."
for ($i = 0; $i -lt $targets.Count; $i++) {
    $idx = $i + 1
    Install-HookToRepo -RepoPath $targets[$i] -Index $idx -Total $targets.Count
}

Show-SummaryTable
