"""TASK-S4-04 委派契约八要素与 task_file 物化 单元测试（§3.9 / §3.10）

覆盖：
- 八要素**缺任一即拒绝**（逐要素单点缺失 + 全缺 + 组合缺），且拒绝原因**点名**缺哪一项
- 「未声明」与「声明为空」的分界（③已有成果 / ④禁止事项空列表合法）
- 质量门：目标过于含糊（< MIN_GOAL_CHARS）、非空约束列表
- task_file 物化格式（八要素平铺 + tenancy/trace/schema_version）与往返一致
- 物化即准入：校验不过**不落盘**（不产生半成品任务文件）
"""

from __future__ import annotations

import json
import os

import pytest

from agent.subagent.delegation import (
    EIGHT_ELEMENTS,
    ELEMENT_LABELS,
    MIN_GOAL_CHARS,
    TASK_FILE_SCHEMA_VERSION,
    DelegationContext,
    DelegationRejected,
    build_task_file,
    delegation_from_task_file,
    element_problems,
    load_task_file,
    require_eight_elements,
    validate_eight_elements,
    write_task_file,
)


def valid_kwargs(**overrides) -> dict:
    """一份合法的八要素（逐项可覆盖为非法值）"""
    data = {
        "goal": "把 docs/zh 下的 12 篇设计稿抽取为可复现步骤序列",
        "constraints": ["只读仓库，不得修改任何文件"],
        "prior_artifacts": ["docs/zh/a.md"],
        "prohibitions": ["不得访问网络"],
        "artifact_format": "JSON Lines：每行 {name, steps[]}",
        "budget_tokens": 20000,
        "timeout_seconds": 300,
        "callback_url": "internal://pipeline/stage2",
    }
    data.update(overrides)
    return data


def make_ctx(**overrides) -> DelegationContext:
    return DelegationContext(**valid_kwargs(**overrides))


# ════════════════════════════════════════════════════════════
#  八要素清单本身
# ════════════════════════════════════════════════════════════


class TestEightElementCatalogue:
    def test_eight_elements_exactly_eight(self):
        assert len(EIGHT_ELEMENTS) == 8

    def test_eight_elements_documented_order(self):
        """顺序即 §3.9 的 ①→⑧"""
        assert EIGHT_ELEMENTS == (
            "goal", "constraints", "prior_artifacts", "prohibitions",
            "artifact_format", "budget_tokens", "timeout_seconds", "callback_url",
        )

    def test_every_element_has_label(self):
        for name in EIGHT_ELEMENTS:
            assert ELEMENT_LABELS.get(name)

    def test_labels_carry_sequence_numbers(self):
        for idx, name in enumerate(EIGHT_ELEMENTS, start=1):
            assert ELEMENT_LABELS[name].startswith(
                "①②③④⑤⑥⑦⑧"[idx - 1])


# ════════════════════════════════════════════════════════════
#  合法上下文
# ════════════════════════════════════════════════════════════


class TestValidContext:
    def test_valid_context_has_no_problems(self):
        assert make_ctx().validate() == ()

    def test_require_valid_returns_self(self):
        ctx = make_ctx()
        assert ctx.require_valid() is ctx

    def test_empty_prior_artifacts_is_declared_not_missing(self):
        """③已有成果：空列表 = 显式声明「无」，不算缺失"""
        assert make_ctx(prior_artifacts=[]).validate() == ()

    def test_empty_prohibitions_is_declared_not_missing(self):
        """④禁止事项：空列表 = 显式声明「无」，不算缺失"""
        assert make_ctx(prohibitions=[]).validate() == ()

    def test_delegation_id_autogenerated(self):
        assert make_ctx().delegation_id.startswith("dlg-")

    def test_delegate_actor_defaults_to_sub_agent_prefix(self):
        """actor 名前缀约定 → actor 矩阵 infer_actor_type 判为 sub_agent"""
        ctx = make_ctx()
        assert ctx.delegate_actor == f"sub_agent:{ctx.delegation_id}"

    def test_sequences_frozen_to_tuple(self):
        ctx = make_ctx(constraints=["a", "b"])
        assert isinstance(ctx.constraints, tuple)

    def test_metadata_defaults_empty(self):
        assert dict(make_ctx().metadata) == {}


# ════════════════════════════════════════════════════════════
#  逐要素缺失 → 拒绝（验收清单第 1 条）
# ════════════════════════════════════════════════════════════


class TestEachElementMissingIsRejected:
    @pytest.mark.parametrize("element", EIGHT_ELEMENTS)
    def test_single_element_none_is_rejected(self, element):
        data = valid_kwargs()
        data[element] = None
        assert validate_eight_elements(data) == (element,)

    @pytest.mark.parametrize("element", EIGHT_ELEMENTS)
    def test_rejection_names_the_element(self, element):
        data = valid_kwargs()
        data[element] = None
        with pytest.raises(DelegationRejected) as excinfo:
            require_eight_elements(data)
        err = excinfo.value
        assert element in err.missing
        assert err.code == "E_DELEGATION_INCOMPLETE"
        assert ELEMENT_LABELS[element] in str(err)

    @pytest.mark.parametrize("element", EIGHT_ELEMENTS)
    def test_context_rejects_each_missing_element(self, element):
        data = valid_kwargs()
        data[element] = None
        with pytest.raises(DelegationRejected) as excinfo:
            DelegationContext(**data).require_valid()
        assert element in excinfo.value.missing

    def test_all_eight_missing_reports_all(self):
        ctx = DelegationContext(
            goal=None, constraints=None, prior_artifacts=None, prohibitions=None,
            artifact_format=None, budget_tokens=None, timeout_seconds=None,
            callback_url=None)
        assert ctx.validate() == EIGHT_ELEMENTS

    def test_rejection_to_dict_has_labels_and_reasons(self):
        with pytest.raises(DelegationRejected) as excinfo:
            require_eight_elements(valid_kwargs(goal=None, budget_tokens=0))
        payload = excinfo.value.to_dict()
        assert payload["code"] == "E_DELEGATION_INCOMPLETE"
        assert set(payload["missing"]) == {"goal", "budget_tokens"}
        assert len(payload["missing_labels"]) == 2
        assert payload["reasons"]["budget_tokens"]

    def test_element_problems_order_follows_catalogue(self):
        problems = element_problems(valid_kwargs(timeout_seconds=None, goal=None))
        assert list(problems.keys()) == ["goal", "timeout_seconds"]


# ════════════════════════════════════════════════════════════
#  质量门：含糊 / 类型错误
# ════════════════════════════════════════════════════════════


class TestQualityGates:
    def test_goal_shorter_than_minimum_rejected(self):
        short = "a" * (MIN_GOAL_CHARS - 1)
        assert validate_eight_elements(valid_kwargs(goal=short)) == ("goal",)

    def test_goal_at_minimum_accepted(self):
        exact = "x" * MIN_GOAL_CHARS
        assert validate_eight_elements(valid_kwargs(goal=exact)) == ()

    def test_whitespace_only_goal_rejected(self):
        assert validate_eight_elements(valid_kwargs(goal="        ")) == ("goal",)

    def test_empty_constraints_rejected(self):
        """②约束为空 = 没写边界，属 §3.9 点名的含糊"""
        assert validate_eight_elements(valid_kwargs(constraints=[])) == ("constraints",)

    def test_constraints_with_blank_item_rejected(self):
        assert validate_eight_elements(valid_kwargs(constraints=["ok", "  "])) == ("constraints",)

    def test_constraints_non_list_rejected(self):
        assert validate_eight_elements(valid_kwargs(constraints="只读")) == ("constraints",)

    def test_prior_artifacts_non_list_rejected(self):
        assert validate_eight_elements(valid_kwargs(prior_artifacts="docs/a.md")) == (
            "prior_artifacts",)

    def test_prohibitions_blank_item_rejected(self):
        assert validate_eight_elements(valid_kwargs(prohibitions=[""])) == ("prohibitions",)

    def test_artifact_format_empty_rejected(self):
        assert validate_eight_elements(valid_kwargs(artifact_format="   ")) == (
            "artifact_format",)

    @pytest.mark.parametrize("bad", [0, -1, 0.5, "100", True])
    def test_budget_tokens_must_be_positive_int(self, bad):
        assert validate_eight_elements(valid_kwargs(budget_tokens=bad)) == ("budget_tokens",)

    @pytest.mark.parametrize("bad", [0, -5, "300"])
    def test_timeout_must_be_positive_number(self, bad):
        assert validate_eight_elements(valid_kwargs(timeout_seconds=bad)) == (
            "timeout_seconds",)

    def test_float_timeout_accepted(self):
        assert validate_eight_elements(valid_kwargs(timeout_seconds=12.5)) == ()

    def test_callback_url_empty_rejected(self):
        assert validate_eight_elements(valid_kwargs(callback_url="  ")) == ("callback_url",)


# ════════════════════════════════════════════════════════════
#  task_file 物化（§3.10）
# ════════════════════════════════════════════════════════════


class TestTaskFileMaterialisation:
    def test_flat_eight_elements_on_top_level(self):
        payload = build_task_file(make_ctx())
        for name in EIGHT_ELEMENTS:
            assert name in payload, name

    def test_schema_and_identifiers(self):
        ctx = make_ctx(tenant_id="t-9", subject_id="u-7", task_id="task-1",
                       trace_id="trace-1", policy_version="p-3")
        payload = build_task_file(ctx)
        assert payload["schema_version"] == TASK_FILE_SCHEMA_VERSION
        assert payload["delegation_id"] == ctx.delegation_id
        assert payload["delegate_actor"] == ctx.delegate_actor
        assert payload["tenancy"] == {"tenant_id": "t-9", "subject_id": "u-7"}
        assert payload["trace"]["trace_id"] == "trace-1"
        assert payload["trace"]["task_id"] == "task-1"
        assert payload["policy_version"] == "p-3"

    def test_lists_are_json_arrays(self):
        payload = build_task_file(make_ctx(constraints=["a", "b"]))
        assert payload["constraints"] == ["a", "b"]
        assert payload["prior_artifacts"] == ["docs/zh/a.md"]

    def test_build_refuses_invalid_context(self):
        ctx = DelegationContext(**valid_kwargs(callback_url=None))
        with pytest.raises(DelegationRejected):
            build_task_file(ctx)

    def test_write_refuses_invalid_and_leaves_no_file(self, tmp_path):
        """物化即准入：不合格不落盘（不产生半成品任务文件）"""
        target = tmp_path / "sub" / "task_file.json"
        ctx = DelegationContext(**valid_kwargs(goal=None))
        with pytest.raises(DelegationRejected):
            write_task_file(ctx, str(target))
        assert not target.exists()
        assert not target.parent.exists()

    def test_write_creates_parent_dirs_and_valid_json(self, tmp_path):
        target = tmp_path / "a" / "b" / "task_file.json"
        path = write_task_file(make_ctx(), str(target))
        assert os.path.isfile(path)
        with open(path, "r", encoding="utf-8") as fh:
            payload = json.load(fh)
        assert payload["goal"].startswith("把 docs/zh")

    def test_write_is_utf8_chinese_preserved(self, tmp_path):
        path = write_task_file(make_ctx(), str(tmp_path / "tf.json"))
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        assert "把 docs/zh" in text

    def test_roundtrip_preserves_elements(self, tmp_path):
        ctx = make_ctx(constraints=["c1", "c2"], prohibitions=["p1"])
        path = write_task_file(ctx, str(tmp_path / "tf.json"))
        restored = delegation_from_task_file(load_task_file(path))
        assert restored.elements() == ctx.elements()
        assert restored.delegation_id == ctx.delegation_id

    def test_roundtrip_preserves_tenancy_and_trace(self, tmp_path):
        ctx = make_ctx(tenant_id="t-1", subject_id="s-1", task_id="tk",
                       trace_id="tr", parent_trace_id="ptr", policy_version="pv")
        path = write_task_file(ctx, str(tmp_path / "tf.json"))
        restored = delegation_from_task_file(load_task_file(path))
        assert restored.tenant_id == "t-1"
        assert restored.subject_id == "s-1"
        assert restored.trace_id == "tr"
        assert restored.parent_trace_id == "ptr"
        assert restored.policy_version == "pv"

    def test_from_task_file_keeps_missing_elements_as_none(self):
        """缺失要素原样透传（不填默认值），使校验能如实点名"""
        restored = delegation_from_task_file({"goal": "足够长的一个目标描述"})
        assert restored.constraints is None
        assert restored.callback_url is None
        assert "constraints" in restored.validate()

    def test_load_task_file_rejects_non_object(self, tmp_path):
        path = tmp_path / "bad.json"
        path.write_text("[1, 2, 3]", encoding="utf-8")
        from agent.subagent.delegation import DelegationError
        with pytest.raises(DelegationError):
            load_task_file(str(path))

    def test_metadata_passthrough(self):
        payload = build_task_file(make_ctx(metadata={"workspace_id": "ws-1"}))
        assert payload["metadata"] == {"workspace_id": "ws-1"}
